import { Component } from "ngjs-core";
const basicTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-basic-rating\",\n    controllerAs: \"example\",\n    templateUrl: \"./basic-rating.component.html\",\n    styleUrl: \"./basic-rating.component.css\",\n})\nexport class BasicRatingComponent {\n    public rating = 3;\n    public setRating(rating: number) { this.rating = rating; }\n}\n";
const basicHtml = "<ngb-rating rate=\"example.rating\" rate-change=\"example.setRating($event)\"></ngb-rating>\n<hr>\n<p class=\"mb-0\">Rate: <strong>{{ example.rating }}</strong></p>\n";
const customTemplateCss = ".star { color: var(--bs-secondary-color); font-size: 2.1rem; padding-right: .15rem; filter: drop-shadow(0 .2rem .35rem rgba(var(--bs-body-color-rgb), .1)); }\n.star.filled { color: var(--bs-warning); }\n.star.filled.low { color: var(--bs-danger); }\n";
const customTemplateTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-rating-custom-template\",\n    controllerAs: \"example\",\n    templateUrl: \"./rating-custom-template.component.html\",\n    styleUrl: \"./rating-custom-template.component.css\",\n})\nexport class RatingCustomTemplateComponent {\n    public rating = 6;\n    public setRating(rating: number) { this.rating = rating; }\n}\n";
const customTemplateHtml = "<p>Bootstrap Icons are rendered through a child <code>ng-template</code>.</p>\n<ngb-rating rate=\"example.rating\" rate-change=\"example.setRating($event)\">\n    <ng-template let-fill=\"fill\" let-index=\"index\">\n        <i class=\"bi star\" ng-class=\"[fill === 100 ? 'bi-star-fill filled' : 'bi-star', { low: index < 3 }]\" aria-hidden=\"true\"></i>\n    </ng-template>\n</ngb-rating>\n<hr>\n<p class=\"mb-0\">Rate: <strong>{{ example.rating }}</strong></p>\n";
const decimalCss = ".heart { color: var(--bs-secondary-bg); display: inline-block; font-size: 2.35rem; margin-right: .15rem; position: relative; filter: drop-shadow(0 .25rem .45rem rgba(var(--bs-body-color-rgb), .1)); }\n.heart .fill { color: var(--bs-danger); left: 0; overflow: hidden; position: absolute; top: 0; }\n";
const decimalTs = "import { Component, type TemplateRef } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-rating-decimal\",\n    controllerAs: \"example\",\n    templateUrl: \"./rating-decimal.component.html\",\n    styleUrl: \"./rating-decimal.component.css\",\n})\nexport class RatingDecimalComponent {\n    public rating = 3.14;\n    public heartTemplate?: TemplateRef<unknown>;\n    public readonly ariaValueText = (current: number, max: number) => `${current} out of ${max} hearts`;\n}\n";
const decimalHtml = "<ng-template ng-ref=\"example.heartTemplate\" let-fill=\"fill\">\n    <span class=\"heart\">\n        <i class=\"bi bi-heart-fill\" aria-hidden=\"true\"></i>\n        <span class=\"fill\" ng-style=\"{ width: fill + '%' }\"><i class=\"bi bi-heart-fill\" aria-hidden=\"true\"></i></span>\n    </span>\n</ng-template>\n\n<ngb-rating rate=\"example.rating\" max=\"5\" readonly=\"true\" star-template=\"example.heartTemplate\" aria-value-text=\"example.ariaValueText\"></ngb-rating>\n<hr>\n<p>Rate: <strong>{{ example.rating }}</strong></p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.rating = 1.35\">1.35</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.rating = 4.72\">4.72</button>\n</div>\n";
const eventsTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-rating-events\",\n    controllerAs: \"example\",\n    templateUrl: \"./rating-events.component.html\",\n    styleUrl: \"./rating-events.component.css\",\n})\nexport class RatingEventsComponent {\n    public selected = 0;\n    public hovered = 0;\n    public readonly = false;\n    public setSelected(value: number) { this.selected = value; }\n    public setHovered(value: number) { this.hovered = value; }\n}\n";
const eventsHtml = "<ngb-rating rate=\"example.selected\" rate-change=\"example.setSelected($event)\" hover=\"example.setHovered($event)\" leave=\"example.setHovered(0)\" readonly=\"example.readonly\"></ngb-rating>\n<hr>\n<dl class=\"row mb-3\">\n    <dt class=\"col-auto\">Selected</dt><dd class=\"col mb-0\">{{ example.selected }}</dd>\n    <dt class=\"col-auto\">Hovered</dt><dd class=\"col mb-0\">{{ example.hovered }}</dd>\n</dl>\n<button type=\"button\" class=\"btn btn-sm\" ng-class=\"example.readonly ? 'btn-outline-danger' : 'btn-outline-success'\" ng-click=\"example.readonly = !example.readonly\">\n    {{ example.readonly ? 'Read-only' : 'Editable' }}\n</button>\n";
const formTs = "import { Component } from \"ngjs-core\";\nimport type { IFormController } from \"angular\";\n\n@Component({\n    selector: \"docs-rating-form\",\n    controllerAs: \"example\",\n    templateUrl: \"./rating-form.component.html\",\n    styleUrl: \"./rating-form.component.css\",\n})\nexport class RatingFormComponent {\n    public rating: number | null = null;\n    public disabled = false;\n    public form?: IFormController;\n\n    public setRating(rating: number) { this.rating = rating; }\n    public clear() { this.rating = null; }\n}\n";
const formHtml = "<form name=\"example.form\" novalidate>\n    <ngb-rating rate=\"example.rating\" rate-change=\"example.setRating($event)\" disabled=\"example.disabled\"></ngb-rating>\n    <input class=\"visually-hidden\" type=\"number\" name=\"rating\" ng-model=\"example.rating\" min=\"1\" required disabled=\"example.disabled\" tabindex=\"-1\" aria-hidden=\"true\">\n\n    <p class=\"small mt-2 mb-3\" ng-class=\"example.form.rating.$valid ? 'text-success' : 'text-danger'\">\n        {{ example.form.rating.$valid ? 'Thanks!' : 'Please rate us' }}\n    </p>\n\n    <p>Model: <strong>{{ example.rating === null ? 'null' : example.rating }}</strong></p>\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-sm\" ng-class=\"example.disabled ? 'btn-outline-danger' : 'btn-outline-success'\" ng-click=\"example.disabled = !example.disabled\">\n            {{ example.disabled ? 'Control disabled' : 'Control enabled' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.clear()\">Clear</button>\n    </div>\n</form>\n";
const globalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbRatingConfig } from \"ngb-js/rating\";\n\n@Component({\n    selector: \"docs-rating-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./rating-global.component.html\",\n    styleUrl: \"./rating-global.component.css\",\n})\nexport class RatingGlobalComponent implements AfterViewInit, OnDestroy {\n    private readonly initialConfig: Pick<NgbRatingConfig, \"max\" | \"readonly\" | \"resettable\" | \"tabindex\">;\n\n    constructor(private readonly config: NgbRatingConfig) {\n        this.initialConfig = {\n            max: config.max,\n            readonly: config.readonly,\n            resettable: config.resettable,\n            tabindex: config.tabindex,\n        };\n        config.max = 5;\n        config.readonly = true;\n        config.resettable = true;\n        config.tabindex = -1;\n    }\n\n    public ngAfterViewInit() { this.restoreConfig(); }\n    public ngOnDestroy() { this.restoreConfig(); }\n    private restoreConfig() { Object.assign(this.config, this.initialConfig); }\n}\n";
const globalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div><p class=\"fw-semibold mb-1\">Customized defaults</p><p class=\"small text-body-secondary mb-0\">Five stars, read-only behavior and no keyboard tab stop.</p></div>\n</div>\n\n<ngb-rating rate=\"3\"></ngb-rating>\n";

@Component({
    selector: "docs-rating-examples-page",
    controllerAs: "$",
    templateUrl: "./rating-examples-page.component.html",
    styleUrl: "./rating-examples-page.component.css",
})
export class RatingExamplesPageComponent {
    public readonly examples = {
        basic: { html: basicHtml, typescript: basicTs },
        events: { html: eventsHtml, typescript: eventsTs },
        customTemplate: { html: customTemplateHtml, typescript: customTemplateTs, css: customTemplateCss },
        decimal: { html: decimalHtml, typescript: decimalTs, css: decimalCss },
        form: { html: formHtml, typescript: formTs },
        global: { html: globalHtml, typescript: globalTs },
    }
}
