import { Component } from "ngjs-core";
const autocloseTs = "import { Component } from \"ngjs-core\";\nimport type { NgbPopover } from \"ngb-js/popover\";\n\n@Component({\n    selector: \"docs-popover-autoclose\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-autoclose.component.html\",\n    styleUrl: \"./popover-autoclose.component.css\",\n})\nexport class PopoverAutocloseComponent {\n    public popover?: NgbPopover;\n}\n";
const autocloseHtml = "<p>Every popover also closes with <kbd>Esc</kbd>.</p>\n<div class=\"vstack gap-3 align-items-start\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" auto-close=\"'inside'\" ngb-popover=\"'Click this content or press Escape'\" popover-title=\"'Inside clicks'\">Close on inside click</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" auto-close=\"'outside'\" ngb-popover=\"'Click elsewhere or press Escape'\" popover-title=\"'Outside clicks'\">Close on outside click</button>\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-outline-secondary\" auto-close=\"true\" ngb-popover=\"'Click anywhere or press Escape'\" popover-title=\"'All clicks'\" ng-ref=\"example.popover\" ng-ref-read=\"ngbPopover\">Close on every click</button>\n        <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"example.popover.toggle()\">External toggle</button>\n    </div>\n</div>\n";
const bodyTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-body\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-body.component.html\",\n    styleUrl: \"./popover-body.component.css\",\n})\nexport class PopoverBodyComponent {}\n";
const bodyHtml = "<div class=\"overflow-hidden border rounded p-4\" style=\"max-width: 24rem\">\n    <p class=\"small text-body-secondary\">This container clips overflowing descendants.</p>\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"'top'\" ngb-popover=\"'Inserted next to the trigger.'\">Default</button>\n        <button type=\"button\" class=\"btn btn-outline-primary\" placement=\"'top'\" ngb-popover=\"'Appended directly to document.body.'\" container=\"'body'\">Append to body</button>\n    </div>\n</div>\n";
const contextTs = "import { Component } from \"ngjs-core\";\nimport type { NgbPopover } from \"ngb-js/popover\";\nimport type { TemplateRef } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-context\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-context.component.html\",\n    styleUrl: \"./popover-context.component.css\",\n})\nexport class PopoverContextComponent {\n    public name = \"World\";\n    public contentTemplate?: TemplateRef<unknown>;\n    public titleTemplate?: TemplateRef<unknown>;\n    public french?: NgbPopover;\n    public german?: NgbPopover;\n    public english?: NgbPopover;\n\n    public toggleWithGreeting(popover: NgbPopover, greeting: string, language: string) {\n        popover.isOpen() ? popover.close() : popover.open({ greeting, language });\n    }\n}\n";
const contextHtml = "<ng-template ng-ref=\"example.contentTemplate\" let-greeting=\"greeting\">{{ greeting }}, <strong>{{ example.name }}</strong>!</ng-template>\n<ng-template ng-ref=\"example.titleTemplate\" let-language=\"language\">Greeting in {{ language }}</ng-template>\n\n<p>You can pass context when manually opening a popover.</p>\n<div class=\"d-flex flex-wrap gap-2 mb-4\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"example.contentTemplate\" popover-title=\"example.titleTemplate\" triggers=\"'manual'\" ng-ref=\"example.french\" ng-ref-read=\"ngbPopover\" ng-click=\"example.toggleWithGreeting(example.french, 'Bonjour', 'French')\">French</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"example.contentTemplate\" popover-title=\"example.titleTemplate\" triggers=\"'manual'\" ng-ref=\"example.german\" ng-ref-read=\"ngbPopover\" ng-click=\"example.toggleWithGreeting(example.german, 'Guten Tag', 'German')\">German</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"example.contentTemplate\" popover-title=\"example.titleTemplate\" triggers=\"'manual'\" ng-ref=\"example.english\" ng-ref-read=\"ngbPopover\" ng-click=\"example.toggleWithGreeting(example.english, 'Hello', 'English')\">English</button>\n</div>\n\n<p>Alternatively, provide a default context through <code>popover-context</code>.</p>\n<button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"example.contentTemplate\" popover-title=\"example.titleTemplate\" popover-context=\"{ language: '中文', greeting: '你好' }\">Chinese</button>\n";
const customClassCss = ".popover-custom { --bs-popover-border-color: var(--bs-primary-border-subtle); --bs-popover-header-bg: var(--bs-primary-bg-subtle); --bs-popover-header-color: var(--bs-primary-text-emphasis); box-shadow: 0 .75rem 2rem rgba(var(--bs-body-color-rgb), .12); }\n";
const customClassTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-custom-class\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-custom-class.component.html\",\n    styleUrl: \"./popover-custom-class.component.css\",\n})\nexport class PopoverCustomClassComponent {}\n";
const customClassHtml = "<button type=\"button\" class=\"btn btn-outline-primary\" ngb-popover=\"'A small custom skin layered on top of Bootstrap variables.'\" popover-title=\"'NgbJS popover'\" popover-class=\"popover-custom\">\n    Popover with custom class\n</button>\n";
const customTargetTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-custom-target\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-custom-target.component.html\",\n    styleUrl: \"./popover-custom-target.component.css\",\n})\nexport class PopoverCustomTargetComponent {}\n";
const customTargetHtml = "<div class=\"d-flex flex-wrap align-items-baseline gap-2\">\n    <span>You can click</span>\n    <button class=\"btn btn-outline-secondary\" type=\"button\" ngb-popover=\"'The button triggered me, but this text positioned me.'\" popover-title=\"'Custom target'\" position-target=\"'#popover-position-target'\">this button</button>\n    <span>but the popover appears over <strong id=\"popover-position-target\" class=\"text-primary\">this target</strong>.</span>\n</div>\n";
const delaysTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-delays\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-delays.component.html\",\n    styleUrl: \"./popover-delays.component.css\",\n})\nexport class PopoverDelaysComponent {}\n";
const delaysHtml = "<p>Move the pointer into the popover before its close delay expires to keep it open.</p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"'Opens after 300 ms and closes after 500 ms.'\" triggers=\"'mouseenter:mouseleave'\" open-delay=\"300\" close-delay=\"500\">300 / 500 ms</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-popover=\"'Opens after one second and closes after two.'\" triggers=\"'mouseenter:mouseleave'\" open-delay=\"1000\" close-delay=\"2000\">1 / 2 seconds</button>\n</div>\n";
const eventsTs = "import { Component } from \"ngjs-core\";\nimport type { NgbPopover } from \"ngb-js/popover\";\n\n@Component({\n    selector: \"docs-popover-events\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-events.component.html\",\n    styleUrl: \"./popover-events.component.css\",\n})\nexport class PopoverEventsComponent {\n    public popover?: NgbPopover;\n    public events: { name: string; time: Date }[] = [];\n    public record(name: string) { this.events.unshift({ name, time: new Date() }); }\n}\n";
const eventsHtml = "<button type=\"button\" class=\"btn btn-outline-primary\" placement=\"'top'\" ngb-popover=\"'Watch the event log below.'\" popover-title=\"'Visibility events'\" shown=\"example.record('shown')\" hidden=\"example.record('hidden')\" ng-ref=\"example.popover\" ng-ref-read=\"ngbPopover\">\n    Toggle popover\n</button>\n\n<div class=\"mt-4\">\n    <p class=\"mb-2\">Current state: <code>{{ example.popover.isOpen() ? 'open' : 'closed' }}</code></p>\n    <ul class=\"list-group list-group-flush\" ng-if=\"example.events.length\">\n        <li class=\"list-group-item px-0 py-2\" ng-repeat=\"event in example.events track by $index\"><code>{{ event.name }}</code> at {{ event.time | date:'mediumTime' }}</li>\n    </ul>\n    <p class=\"text-body-secondary mb-0\" ng-if=\"!example.events.length\">No events recorded yet.</p>\n</div>\n";
const globalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbPopoverConfig } from \"ngb-js/popover\";\n\n@Component({\n    selector: \"docs-popover-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-global.component.html\",\n    styleUrl: \"./popover-global.component.css\",\n})\nexport class PopoverGlobalComponent implements AfterViewInit, OnDestroy {\n    private readonly initialConfig: Pick<NgbPopoverConfig, \"container\" | \"openDelay\" | \"placement\" | \"triggers\">;\n\n    constructor(private readonly config: NgbPopoverConfig) {\n        this.initialConfig = {\n            container: config.container,\n            openDelay: config.openDelay,\n            placement: config.placement,\n            triggers: config.triggers,\n        };\n        config.container = \"body\";\n        config.openDelay = 300;\n        config.placement = \"end\";\n        config.triggers = \"mouseenter:mouseleave\";\n    }\n\n    public ngAfterViewInit() { this.restoreConfig(); }\n    public ngOnDestroy() { this.restoreConfig(); }\n    private restoreConfig() {\n        this.config.container = this.initialConfig.container;\n        this.config.openDelay = this.initialConfig.openDelay;\n        this.config.placement = this.initialConfig.placement;\n        this.config.triggers = this.initialConfig.triggers;\n    }\n}\n";
const globalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div><p class=\"fw-semibold mb-1\">Global defaults used by this example</p><p class=\"small text-body-secondary mb-0\">Hover trigger, end placement, body container and a 300 ms opening delay.</p></div>\n</div>\n<button type=\"button\" class=\"btn btn-outline-primary\" ngb-popover=\"'This instance reads every option from NgbPopoverConfig.'\" popover-title=\"'Configured globally'\">Hover over me</button>\n";
const manualTs = "import { Component } from \"ngjs-core\";\nimport type { NgbPopover } from \"ngb-js/popover\";\n\n@Component({\n    selector: \"docs-popover-manual-control\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-manual-control.component.html\",\n    styleUrl: \"./popover-manual-control.component.css\",\n})\nexport class PopoverManualControlComponent {\n    public popover?: NgbPopover;\n}\n";
const manualHtml = "<button type=\"button\" class=\"btn btn-primary mb-3\" ngb-popover=\"'This target is controlled by the buttons below'\" popover-title=\"'External controls'\" triggers=\"'manual'\" auto-close=\"false\" ng-ref=\"example.popover\" ng-ref-read=\"ngbPopover\">\n    Popover target\n</button>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.popover.open()\">Open</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.popover.close()\">Close</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.popover.toggle()\">Toggle</button>\n</div>\n";
const placementsTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-placements\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-placements.component.html\",\n    styleUrl: \"./popover-placements.component.css\",\n})\nexport class PopoverPlacementsComponent {}\n";
const placementsHtml = "<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"'top'\" ngb-popover=\"'Popover content'\" popover-title=\"'Popover on top'\">Top</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"'end'\" ngb-popover=\"'Popover content'\" popover-title=\"'Popover on right'\">Right</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"'bottom'\" ngb-popover=\"'Popover content'\" popover-title=\"'Popover on bottom'\">Bottom</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"'start'\" ngb-popover=\"'Popover content'\" popover-title=\"'Popover on left'\">Left</button>\n</div>\n";
const templateTs = "import { Component } from \"ngjs-core\";\nimport type { TemplateRef } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-popover-template\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-template.component.html\",\n    styleUrl: \"./popover-template.component.css\",\n})\nexport class PopoverTemplateComponent {\n    public name = \"NgbJS\";\n    public contentTemplate?: TemplateRef<unknown>;\n    public titleTemplate?: TemplateRef<unknown>;\n}\n";
const templateHtml = "<ng-template ng-ref=\"example.titleTemplate\">\n    <span class=\"d-flex align-items-center gap-2\"><i class=\"bi bi-code-slash\" aria-hidden=\"true\"></i><strong>Template content</strong></span>\n</ng-template>\n<ng-template ng-ref=\"example.contentTemplate\">\n    <p class=\"mb-2\">Hello, <strong>{{ example.name }}</strong>!</p>\n    <button class=\"btn btn-sm btn-primary\" type=\"button\" ng-click=\"example.name = 'AngularJS'\">Update binding</button>\n</ng-template>\n\n<button type=\"button\" class=\"btn btn-outline-primary\" ngb-popover=\"example.contentTemplate\" popover-title=\"example.titleTemplate\">\n    HTML and bindings\n</button>\n";
const triggersTs = "import { Component } from \"ngjs-core\";\nimport type { NgbPopover } from \"ngb-js/popover\";\n\n@Component({\n    selector: \"docs-popover-triggers\",\n    controllerAs: \"example\",\n    templateUrl: \"./popover-triggers.component.html\",\n    styleUrl: \"./popover-triggers.component.css\",\n})\nexport class PopoverTriggersComponent {\n    public manual?: NgbPopover;\n}\n";
const triggersHtml = "<p class=\"mb-3\">Custom events can be paired as <code>mouseenter:mouseleave</code>.</p>\n<button type=\"button\" class=\"btn btn-outline-secondary mb-4\" ngb-popover=\"'Shown while the pointer is over the trigger'\" popover-title=\"'Hover trigger'\" triggers=\"'mouseenter:mouseleave'\">\n    Hover over me\n</button>\n\n<p class=\"mb-3\">A manual trigger delegates opening and closing to application code.</p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-primary\" ngb-popover=\"'Manually controlled content'\" popover-title=\"'Manual popover'\" triggers=\"'manual'\" auto-close=\"false\" ng-ref=\"example.manual\" ng-ref-read=\"ngbPopover\" ng-click=\"example.manual.open()\">\n        Open popover\n    </button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.manual.close()\">Close popover</button>\n</div>\n";

@Component({
    selector: "docs-popover-examples-page",
    controllerAs: "$",
    templateUrl: "./popover-examples-page.component.html",
    styleUrl: "./popover-examples-page.component.css",
})
export class PopoverExamplesPageComponent {
    public readonly examples = {
        placements: { html: placementsHtml, typescript: placementsTs },
        template: { html: templateHtml, typescript: templateTs },
        triggers: { html: triggersHtml, typescript: triggersTs },
        manual: { html: manualHtml, typescript: manualTs },
        autoclose: { html: autocloseHtml, typescript: autocloseTs },
        context: { html: contextHtml, typescript: contextTs },
        customTarget: { html: customTargetHtml, typescript: customTargetTs },
        delays: { html: delaysHtml, typescript: delaysTs },
        events: { html: eventsHtml, typescript: eventsTs },
        body: { html: bodyHtml, typescript: bodyTs },
        customClass: { html: customClassHtml, typescript: customClassTs, css: customClassCss },
        global: { html: globalHtml, typescript: globalTs },
    }
}
