import { Component } from "ngjs-core";
const dropdownDisabledItemsTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-dropdown-disabled-items\",\n    controllerAs: \"example\",\n    templateUrl: \"./dropdown-disabled-items.component.html\",\n    styleUrl: \"./dropdown-disabled-items.component.css\",\n})\nexport class DropdownDisabledItemsComponent {\n    public restricted = true;\n}\n";
const dropdownFormTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-dropdown-form\",\n    controllerAs: \"example\",\n    templateUrl: \"./dropdown-form.component.html\",\n    styleUrl: \"./dropdown-form.component.css\",\n})\nexport class DropdownFormComponent {\n    public email = \"\";\n    public remember = false;\n    public submitted = false;\n\n    public submit() {\n        this.submitted = true;\n    }\n}\n";
const dropdownGlobalTs = "import { Component, type OnDestroy } from \"ngjs-core\";\nimport { NgbDropdownConfig } from \"ngb-js/dropdown\";\n\n@Component({\n    selector: \"docs-dropdown-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./dropdown-global.component.html\",\n    styleUrl: \"./dropdown-global.component.css\",\n})\nexport class DropdownGlobalComponent implements OnDestroy {\n    private readonly initialConfig: Pick<NgbDropdownConfig, \"autoClose\" | \"container\" | \"placement\">;\n\n    constructor(private readonly config: NgbDropdownConfig) {\n        this.initialConfig = {\n            autoClose: config.autoClose,\n            container: config.container,\n            placement: config.placement,\n        };\n\n        config.autoClose = \"outside\";\n        config.container = \"body\";\n        config.placement = [\"top-start\", \"bottom-start\"];\n    }\n\n    public ngOnDestroy() {\n        this.config.autoClose = this.initialConfig.autoClose;\n        this.config.container = this.initialConfig.container;\n        this.config.placement = this.initialConfig.placement;\n    }\n}\n";
const manualDropdownTs = "import { Component, ViewChild } from \"ngjs-core\";\nimport { NgbDropdown } from \"ngb-js/dropdown\";\n\n@Component({\n    selector: \"docs-manual-dropdown\",\n    controllerAs: \"example\",\n    templateUrl: \"./manual-dropdown.component.html\",\n    styleUrl: \"./manual-dropdown.component.css\",\n})\nexport class ManualDropdownComponent {\n    @ViewChild(\"dropdown\", { static: true })\n    private dropdown!: NgbDropdown;\n\n    public opened = false;\n\n    public open() {\n        this.dropdown.open();\n    }\n\n    public close() {\n        this.dropdown.close();\n    }\n\n    public toggle() {\n        this.dropdown.toggle();\n    }\n}\n";
const simpleDropdownHtml = "<div class=\"d-flex flex-wrap align-items-center gap-3 py-5\">\n    <div ngb-dropdown placement=\"'bottom-start'\">\n        <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Bottom dropdown</button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Profile</button>\n            <button type=\"button\" ngb-dropdown-item>Settings</button>\n            <div class=\"dropdown-divider\"></div>\n            <button type=\"button\" ngb-dropdown-item>Sign out</button>\n        </div>\n    </div>\n\n    <div ngb-dropdown placement=\"'top-start'\">\n        <button type=\"button\" class=\"btn btn-outline-primary\" ngb-dropdown-toggle>Top dropdown</button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Newest first</button>\n            <button type=\"button\" ngb-dropdown-item>Oldest first</button>\n            <button type=\"button\" ngb-dropdown-item>Recently updated</button>\n        </div>\n    </div>\n</div>\n";
const manualDropdownHtml = "<div class=\"d-flex flex-wrap gap-2 mb-3\">\n    <button type=\"button\" class=\"btn btn-primary btn-sm\" ng-click=\"example.open()\">Open</button>\n    <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"example.close()\">Close</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary btn-sm\" ng-click=\"example.toggle()\">Toggle</button>\n</div>\n\n<div\n    ngb-dropdown\n    ng-ref=\"dropdown\"\n    ng-ref-read=\"ngbDropdown\"\n    open=\"example.opened\"\n    open-change=\"example.opened = $event\">\n    <button type=\"button\" class=\"btn btn-outline-dark\" ngb-dropdown-anchor>\n        Manually controlled menu\n    </button>\n    <div ngb-dropdown-menu>\n        <button type=\"button\" ngb-dropdown-item>First action</button>\n        <button type=\"button\" ngb-dropdown-item>Second action</button>\n    </div>\n</div>\n\n<p class=\"small text-body-secondary mt-2 mb-0\">\n    Current state: {{ example.opened ? 'open' : 'closed' }}\n</p>\n";
const dropdownButtonGroupsHtml = "<div class=\"d-flex flex-wrap gap-3\">\n    <div class=\"btn-group\" ngb-dropdown>\n        <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Button group</button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Edit</button>\n            <button type=\"button\" ngb-dropdown-item>Duplicate</button>\n            <button type=\"button\" ngb-dropdown-item>Archive</button>\n        </div>\n    </div>\n\n    <div class=\"btn-group\" ngb-dropdown>\n        <button type=\"button\" class=\"btn btn-success\">Save</button>\n        <button\n            type=\"button\"\n            class=\"btn btn-success dropdown-toggle-split\"\n            ngb-dropdown-toggle\n            aria-label=\"More save options\">\n            <span class=\"visually-hidden\">Toggle dropdown</span>\n        </button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Save as draft</button>\n            <button type=\"button\" ngb-dropdown-item>Save and publish</button>\n            <button type=\"button\" ngb-dropdown-item>Save a copy</button>\n        </div>\n    </div>\n</div>\n";
const dropdownDisabledItemsHtml = "<div class=\"form-check form-switch mb-3\">\n    <input\n        class=\"form-check-input\"\n        type=\"checkbox\"\n        role=\"switch\"\n        id=\"dropdown-restricted-items\"\n        ng-model=\"example.restricted\">\n    <label class=\"form-check-label\" for=\"dropdown-restricted-items\">Disable restricted actions</label>\n</div>\n\n<div ngb-dropdown>\n    <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Project actions</button>\n    <div ngb-dropdown-menu>\n        <button type=\"button\" ngb-dropdown-item>Open project</button>\n        <button type=\"button\" ngb-dropdown-item disabled=\"example.restricted\">Archive project</button>\n        <button type=\"button\" ngb-dropdown-item disabled=\"example.restricted\">Delete project</button>\n        <div class=\"dropdown-divider\"></div>\n        <button type=\"button\" ngb-dropdown-item disabled=\"true\">Unavailable action</button>\n    </div>\n</div>\n";
const dropdownFormHtml = "<div ngb-dropdown auto-close=\"'outside'\">\n    <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Sign in</button>\n    <div ngb-dropdown-menu class=\"p-3\">\n        <form ng-submit=\"example.submit()\">\n            <div class=\"mb-3\">\n                <label class=\"form-label\" for=\"dropdown-form-email\">Email address</label>\n                <input\n                    id=\"dropdown-form-email\"\n                    type=\"email\"\n                    class=\"form-control\"\n                    placeholder=\"name@example.com\"\n                    ng-model=\"example.email\"\n                    required>\n            </div>\n            <div class=\"form-check mb-3\">\n                <input\n                    id=\"dropdown-form-remember\"\n                    type=\"checkbox\"\n                    class=\"form-check-input\"\n                    ng-model=\"example.remember\">\n                <label class=\"form-check-label\" for=\"dropdown-form-remember\">Remember me</label>\n            </div>\n            <button type=\"submit\" class=\"btn btn-primary w-100\">Continue</button>\n            <p class=\"small text-success mt-2 mb-0\" ng-if=\"example.submitted\">Form submitted.</p>\n        </form>\n    </div>\n</div>\n";
const dropdownBodyHtml = "<div class=\"border rounded p-3 overflow-hidden\">\n    <p class=\"small text-body-secondary mb-3\">\n        The wrapper clips overflowing content, but the menu is appended to the document body.\n    </p>\n\n    <div ngb-dropdown container=\"body\">\n        <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Open body container</button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Account</button>\n            <button type=\"button\" ngb-dropdown-item>Notifications</button>\n            <button type=\"button\" ngb-dropdown-item>Privacy</button>\n        </div>\n    </div>\n</div>\n";
const dropdownNavbarHtml = "<nav class=\"navbar bg-body-tertiary border rounded px-3\">\n    <span class=\"navbar-brand mb-0\">Workspace</span>\n\n    <div class=\"ms-auto\" ngb-dropdown display=\"dynamic\" placement=\"'bottom-end'\">\n        <button type=\"button\" class=\"btn btn-outline-primary\" ngb-dropdown-toggle>Account</button>\n        <div ngb-dropdown-menu>\n            <button type=\"button\" ngb-dropdown-item>Profile</button>\n            <button type=\"button\" ngb-dropdown-item>Preferences</button>\n            <div class=\"dropdown-divider\"></div>\n            <button type=\"button\" ngb-dropdown-item>Sign out</button>\n        </div>\n    </div>\n</nav>\n";
const dropdownGlobalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">\n            The menu prefers the top placement, uses the body container and closes only after an outside click.\n        </p>\n    </div>\n</div>\n\n<div ngb-dropdown>\n    <button type=\"button\" class=\"btn btn-primary\" ngb-dropdown-toggle>Globally configured</button>\n    <div ngb-dropdown-menu>\n        <button type=\"button\" ngb-dropdown-item>This click keeps the menu open</button>\n        <button type=\"button\" ngb-dropdown-item>So does this one</button>\n    </div>\n</div>\n";

@Component({
    selector: "docs-dropdown-examples-page",
    controllerAs: "$",
    templateUrl: "./dropdown-examples-page.component.html",
    styleUrl: "./dropdown-examples-page.component.css",
})
export class DropdownExamplesPageComponent {
    public readonly examples = {
        simple: {
            html: simpleDropdownHtml,
        },
        manual: {
            html: manualDropdownHtml,
            typescript: manualDropdownTs,
        },
        buttonGroups: {
            html: dropdownButtonGroupsHtml,
        },
        disabledItems: {
            html: dropdownDisabledItemsHtml,
            typescript: dropdownDisabledItemsTs,
        },
        form: {
            html: dropdownFormHtml,
            typescript: dropdownFormTs,
        },
        body: {
            html: dropdownBodyHtml,
        },
        navbar: {
            html: dropdownNavbarHtml,
        },
        global: {
            html: dropdownGlobalHtml,
            typescript: dropdownGlobalTs,
        },
    }
}
