import { Component } from "ngjs-core";
const modalComponentContentTs = "import { Component } from \"ngjs-core\";\nimport { ModalDemoContentComponent } from \"@/features/modal/components/modal-demo-content/modal-demo-content.component\"\nimport { NgbModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-component-content\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-component-content.component.html\",\n    styleUrl: \"./modal-component-content.component.css\",\n})\nexport class ModalComponentContentComponent {\n    public lastResult = \"No result yet\";\n\n    constructor(private readonly modal: NgbModal) {}\n\n    public async open() {\n        const modalRef = await this.modal.open(ModalDemoContentComponent, {\n            bindings: {\n                title: \"Component as content\",\n                description: \"NgbActiveModal is provided directly to the content component.\",\n            },\n        });\n\n        modalRef.closed.subscribe((result) => {\n            this.lastResult = `Closed with: ${result}`;\n        });\n\n        modalRef.dismissed.subscribe((reason) => {\n            this.lastResult = `Dismissed with: ${reason}`;\n        });\n    }\n}\n";
const modalDefaultTs = "import { Component, TemplateRef, ViewChild } from \"ngjs-core\";\nimport { NgbModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-default\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-default.component.html\",\n    styleUrl: \"./modal-default.component.css\",\n})\nexport class ModalDefaultComponent {\n    @ViewChild(\"content\", { read: TemplateRef, static: true })\n    private content!: TemplateRef<unknown>;\n\n    constructor(private readonly modal: NgbModal) {}\n\n    public open() {\n        this.modal.open(this.content);\n    }\n}\n";
const modalDemoContentTs = "import { Component, Input } from \"ngjs-core\";\nimport type { NgbActiveModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-demo-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./modal-demo-content.component.html\",\n    styleUrl: \"./modal-demo-content.component.css\",\n})\nexport class ModalDemoContentComponent {\n    @Input({ required: true }) ngbActiveModal!: NgbActiveModal;\n    @Input() title = \"Component modal\";\n    @Input() description = \"This modal receives a component as its content.\";\n    @Input() longContent = false;\n    public readonly items = Array.from({ length: 24 }, (_, index) => `Scrollable content row ${index + 1}`);\n}\n";
const modalFocusTs = "import { Component } from \"ngjs-core\";\nimport { ModalFocusContentComponent } from \"@/features/modal/components/modal-focus-content/modal-focus-content.component\"\nimport { NgbModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-focus\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-focus.component.html\",\n    styleUrl: \"./modal-focus.component.css\",\n})\nexport class ModalFocusComponent {\n    constructor(private readonly modal: NgbModal) {}\n\n    public openDefaultFocus() {\n        this.modal.open(ModalFocusContentComponent, {\n            ariaLabelledBy: \"modal-focus-title\",\n            bindings: { autofocus: false },\n        });\n    }\n\n    public openCustomFocus() {\n        this.modal.open(ModalFocusContentComponent, {\n            ariaLabelledBy: \"modal-focus-title\",\n            bindings: { autofocus: true },\n        });\n    }\n}\n";
const modalFocusContentTs = "import { Component, Input } from \"ngjs-core\";\nimport type { NgbActiveModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-focus-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./modal-focus-content.component.html\",\n    styleUrl: \"./modal-focus-content.component.css\",\n})\nexport class ModalFocusContentComponent {\n    @Input({ required: true }) ngbActiveModal!: NgbActiveModal;\n    @Input() autofocus = false;\n}\n";
const modalGlobalTs = "import { Component, type OnDestroy } from \"ngjs-core\";\nimport { ModalDemoContentComponent } from \"@/features/modal/components/modal-demo-content/modal-demo-content.component\"\nimport { NgbModal, NgbModalConfig } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-global.component.html\",\n    styleUrl: \"./modal-global.component.css\",\n})\nexport class ModalGlobalComponent implements OnDestroy {\n    private readonly initialConfig: Pick<NgbModalConfig, \"backdrop\" | \"centered\" | \"keyboard\" | \"size\">;\n\n    constructor(\n        private readonly modal: NgbModal,\n        private readonly config: NgbModalConfig,\n    ) {\n        this.initialConfig = {\n            backdrop: config.backdrop,\n            centered: config.centered,\n            keyboard: config.keyboard,\n            size: config.size,\n        };\n\n    }\n\n    public async open() {\n        this.applyConfig();\n\n        try {\n            await this.modal.open(ModalDemoContentComponent, {\n                bindings: {\n                    title: \"Globally configured modal\",\n                    description: \"This modal is centered, large and cannot be dismissed with Escape or a backdrop click.\",\n                },\n            });\n        } finally {\n            this.restoreConfig();\n        }\n    }\n\n    public ngOnDestroy() {\n        this.restoreConfig();\n    }\n\n    private applyConfig() {\n        this.config.backdrop = \"static\";\n        this.config.centered = true;\n        this.config.keyboard = false;\n        this.config.size = \"lg\";\n    }\n\n    private restoreConfig() {\n        this.config.backdrop = this.initialConfig.backdrop;\n        this.config.centered = this.initialConfig.centered;\n        this.config.keyboard = this.initialConfig.keyboard;\n        this.config.size = this.initialConfig.size;\n    }\n}\n";
const modalOptionsCss = ".window .modal-content { border-top: .35rem solid var(--bs-primary); box-shadow: 0 1.5rem 4rem rgba(var(--bs-body-color-rgb), .2); }\n.backdrop, .updated-backdrop { --bs-backdrop-bg: var(--bs-danger); --bs-backdrop-opacity: .35; }\n.dialog .modal-content, .updated-dialog .modal-content { border-radius: 1.5rem; border-color: var(--bs-primary-border-subtle); box-shadow: 0 1rem 3rem rgba(var(--bs-primary-rgb), .18); }\n.updated-window .modal-content { border-color: var(--bs-success); box-shadow: 0 1rem 3rem rgba(var(--bs-body-color-rgb), .18); }\n";
const modalOptionsTs = "import { Component } from \"ngjs-core\";\nimport { ModalDemoContentComponent } from \"@/features/modal/components/modal-demo-content/modal-demo-content.component\"\nimport { NgbModal, type NgbModalOptions } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-options\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-options.component.html\",\n    styleUrl: \"./modal-options.component.css\",\n})\nexport class ModalOptionsComponent {\n    constructor(private readonly modal: NgbModal) {}\n\n    public openCustomWindow() {\n        this.open(\"Custom window class\", { windowClass: \"window\" });\n    }\n\n    public openStaticBackdrop() {\n        this.open(\"Static custom backdrop\", {\n            backdrop: \"static\",\n            backdropClass: \"backdrop\",\n            keyboard: false,\n        });\n    }\n\n    public openSmall() {\n        this.open(\"Small modal\", { size: \"sm\" });\n    }\n\n    public openLarge() {\n        this.open(\"Large modal\", { size: \"lg\" });\n    }\n\n    public openExtraLarge() {\n        this.open(\"Extra large modal\", { size: \"xl\" });\n    }\n\n    public openFullscreen() {\n        this.open(\"Fullscreen modal\", { fullscreen: true });\n    }\n\n    public openCentered() {\n        this.open(\"Vertically centered modal\", { centered: true });\n    }\n\n    public openScrollable() {\n        this.open(\"Scrollable modal\", { scrollable: true, size: \"lg\" }, true);\n    }\n\n    public openCustomDialog() {\n        this.open(\"Custom dialog class\", { modalDialogClass: \"dialog\" });\n    }\n\n    private open(title: string, options: NgbModalOptions, longContent = false) {\n        this.modal.open(ModalDemoContentComponent, {\n            ...options,\n            bindings: {\n                title,\n                description: \"These values are applied only to this modal instance.\",\n                longContent,\n            },\n        });\n    }\n}\n";
const modalStackedTs = "import { Component } from \"ngjs-core\";\nimport { ModalStackedContentComponent } from \"@/features/modal/components/modal-stacked-content/modal-stacked-content.component\"\nimport { NgbModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-stacked\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-stacked.component.html\",\n    styleUrl: \"./modal-stacked.component.css\",\n})\nexport class ModalStackedComponent {\n    constructor(private readonly modal: NgbModal) {}\n\n    public async openStack() {\n        for (let level = 1; level <= 3; level++) {\n            await this.modal.open(ModalStackedContentComponent, {\n                bindings: {\n                    level,\n                },\n            });\n        }\n    }\n}\n";
const modalStackedContentTs = "import { Component, Input } from \"ngjs-core\";\nimport { NgbModal, type NgbActiveModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-stacked-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./modal-stacked-content.component.html\",\n    styleUrl: \"./modal-stacked-content.component.css\",\n})\nexport class ModalStackedContentComponent {\n    @Input({ required: true }) ngbActiveModal!: NgbActiveModal;\n    @Input() level = 1;\n\n    constructor(private readonly modal: NgbModal) {}\n\n    public dismissAll() {\n        this.modal.dismissAll(\"Dismiss all\");\n    }\n}\n";
const modalUpdatableTs = "import { Component } from \"ngjs-core\";\nimport { ModalUpdatableContentComponent } from \"@/features/modal/components/modal-updatable-content/modal-updatable-content.component\"\nimport { NgbModal } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-updatable\",\n    controllerAs: \"example\",\n    templateUrl: \"./modal-updatable.component.html\",\n    styleUrl: \"./modal-updatable.component.css\",\n})\nexport class ModalUpdatableComponent {\n    constructor(private readonly modal: NgbModal) {}\n\n    public open() {\n        this.modal.open(ModalUpdatableContentComponent, {\n            ariaLabelledBy: \"updatable-modal-title\",\n            ariaDescribedBy: \"updatable-modal-description\",\n            size: \"sm\",\n        });\n    }\n}\n";
const modalUpdatableContentTs = "import { Component, Input } from \"ngjs-core\";\nimport type { NgbActiveModal, NgbModalUpdatableOptions } from \"ngb-js/modal\";\n\n@Component({\n    selector: \"docs-modal-updatable-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./modal-updatable-content.component.html\",\n    styleUrl: \"./modal-updatable-content.component.css\",\n})\nexport class ModalUpdatableContentComponent {\n    @Input({ required: true }) ngbActiveModal!: NgbActiveModal;\n    public ariaReferences = true;\n    public centered = false;\n    public fullscreen = false;\n    public customBackdrop = false;\n    public size: NgbModalUpdatableOptions[\"size\"] = \"sm\";\n    public customWindow = false;\n    public customDialog = false;\n\n    public toggleAriaReferences() {\n        this.ariaReferences = !this.ariaReferences;\n        this.ngbActiveModal.update({\n            ariaLabelledBy: this.ariaReferences ? \"updatable-modal-title\" : \"\",\n            ariaDescribedBy: this.ariaReferences ? \"updatable-modal-description\" : \"\",\n        });\n    }\n\n    public toggleCentered() {\n        this.centered = !this.centered;\n        this.ngbActiveModal.update({ centered: this.centered });\n    }\n\n    public toggleFullscreen() {\n        this.fullscreen = !this.fullscreen;\n        this.ngbActiveModal.update({ fullscreen: this.fullscreen });\n    }\n\n    public toggleBackdropClass() {\n        this.customBackdrop = !this.customBackdrop;\n        this.ngbActiveModal.update({ backdropClass: this.customBackdrop ? \"updated-backdrop\" : \"\" });\n    }\n\n    public cycleSize() {\n        const sizes: Array<NgbModalUpdatableOptions[\"size\"]> = [\"sm\", \"lg\", \"xl\"];\n        this.size = sizes[(sizes.indexOf(this.size) + 1) % sizes.length];\n        this.ngbActiveModal.update({ size: this.size });\n    }\n\n    public toggleWindowClass() {\n        this.customWindow = !this.customWindow;\n        this.ngbActiveModal.update({ windowClass: this.customWindow ? \"updated-window\" : \"\" });\n    }\n\n    public toggleDialogClass() {\n        this.customDialog = !this.customDialog;\n        this.ngbActiveModal.update({ modalDialogClass: this.customDialog ? \"updated-dialog\" : \"\" });\n    }\n}\n";
const modalDefaultHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open default modal</button>\n\n<ng-template ng-ref=\"content\" let-close=\"close\" let-dismiss=\"dismiss\">\n    <div class=\"modal-header\">\n        <h2 class=\"modal-title fs-5\">Default modal</h2>\n        <button type=\"button\" class=\"btn-close\" aria-label=\"Close\" ng-click=\"dismiss('header close')\"></button>\n    </div>\n    <div class=\"modal-body\">\n        <p class=\"mb-0\">This modal uses the global defaults without passing local options.</p>\n    </div>\n    <div class=\"modal-footer\">\n        <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"dismiss('cancel')\">Cancel</button>\n        <button type=\"button\" class=\"btn btn-primary\" ng-click=\"close('accepted')\">Continue</button>\n    </div>\n</ng-template>\n";
const modalComponentContentHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open component modal</button>\n<p class=\"small text-body-secondary mt-2 mb-0\">{{ example.lastResult }}</p>\n";
const modalDemoContentHtml = "<div class=\"modal-header\">\n    <h2 class=\"modal-title fs-5\">{{ $.title }}</h2>\n    <button\n        type=\"button\"\n        class=\"btn-close\"\n        aria-label=\"Close\"\n        ng-click=\"$.ngbActiveModal.dismiss('header close')\">\n    </button>\n</div>\n\n<div class=\"modal-body\">\n    <p ng-class=\"{ 'mb-0': !$.longContent }\">{{ $.description }}</p>\n\n    <div class=\"list-group\" ng-if=\"$.longContent\">\n        <div class=\"list-group-item\" ng-repeat=\"item in $.items track by $index\">{{ item }}</div>\n    </div>\n</div>\n\n<div class=\"modal-footer\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"$.ngbActiveModal.dismiss('cancel')\">\n        Cancel\n    </button>\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveModal.close('accepted')\">\n        Continue\n    </button>\n</div>\n";
const modalFocusHtml = "<p class=\"text-body-secondary\">\n    The first focusable element receives focus by default. Add <code>ngbAutofocus</code> to choose another target.\n</p>\n\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.openDefaultFocus()\">\n        Focus first element\n    </button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCustomFocus()\">\n        Use ngbAutofocus\n    </button>\n</div>\n";
const modalFocusContentHtml = "<div class=\"modal-header\">\n    <h2 class=\"modal-title fs-5\" id=\"modal-focus-title\">Focus management</h2>\n</div>\n\n<div class=\"modal-body\">\n    <div class=\"mb-3\">\n        <label class=\"form-label\" for=\"modal-first-focusable\">First focusable element</label>\n        <input id=\"modal-first-focusable\" type=\"text\" class=\"form-control\" placeholder=\"Focused by default\">\n    </div>\n\n    <div ng-if=\"$.autofocus\">\n        <label class=\"form-label\" for=\"modal-custom-autofocus\">Custom autofocus target</label>\n        <input\n            id=\"modal-custom-autofocus\"\n            type=\"text\"\n            class=\"form-control\"\n            placeholder=\"Focused through ngbAutofocus\"\n            ngbAutofocus>\n    </div>\n</div>\n\n<div class=\"modal-footer\">\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveModal.close()\">Done</button>\n</div>\n";
const modalOptionsHtml = "<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCustomWindow()\">Custom class</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openStaticBackdrop()\">Static backdrop</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openSmall()\">Small</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openLarge()\">Large</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openExtraLarge()\">Extra large</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openFullscreen()\">Fullscreen</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCentered()\">Vertically centered</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openScrollable()\">Scrollable content</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCustomDialog()\">Dialog custom class</button>\n</div>\n";
const modalUpdatableHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open updatable modal</button>\n";
const modalUpdatableContentHtml = "<div class=\"modal-header\">\n    <h2 class=\"modal-title fs-5\" id=\"updatable-modal-title\">Updatable options</h2>\n    <button type=\"button\" class=\"btn-close\" aria-label=\"Close\" ng-click=\"$.ngbActiveModal.dismiss('close')\"></button>\n</div>\n\n<div class=\"modal-body\">\n    <p id=\"updatable-modal-description\">\n        Change the window, dialog, backdrop and accessibility options while this modal remains open.\n    </p>\n\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleAriaReferences()\">\n            ARIA references: {{ $.ariaReferences ? 'on' : 'off' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleCentered()\">\n            Centered: {{ $.centered ? 'on' : 'off' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleFullscreen()\">\n            Fullscreen: {{ $.fullscreen ? 'on' : 'off' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleBackdropClass()\">\n            Backdrop class: {{ $.customBackdrop ? 'on' : 'off' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.cycleSize()\">\n            Size: {{ $.size }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleWindowClass()\">\n            Window class: {{ $.customWindow ? 'on' : 'off' }}\n        </button>\n        <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"$.toggleDialogClass()\">\n            Dialog class: {{ $.customDialog ? 'on' : 'off' }}\n        </button>\n    </div>\n</div>\n\n<div class=\"modal-footer\">\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveModal.close()\">Done</button>\n</div>\n";
const modalStackedHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.openStack()\">Open three modals</button>\n";
const modalStackedContentHtml = "<div class=\"modal-header\">\n    <h2 class=\"modal-title fs-5\">Stacked modal {{ $.level }}</h2>\n    <button type=\"button\" class=\"btn-close\" aria-label=\"Close\" ng-click=\"$.ngbActiveModal.dismiss('close')\"></button>\n</div>\n\n<div class=\"modal-body\">\n    <p class=\"mb-0\">This is modal layer {{ $.level }} of 3. Close it to return to the previous layer.</p>\n</div>\n\n<div class=\"modal-footer\">\n    <button type=\"button\" class=\"btn btn-outline-danger\" ng-click=\"$.dismissAll()\">Dismiss all</button>\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveModal.close()\">Close this modal</button>\n</div>\n";
const modalGlobalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">\n            Modals are large, vertically centered, use a static backdrop and ignore the Escape key.\n            This documentation example restores the shared defaults immediately after opening.\n        </p>\n    </div>\n</div>\n\n<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open globally configured modal</button>\n";

@Component({
    selector: "docs-modal-examples-page",
    controllerAs: "$",
    templateUrl: "./modal-examples-page.component.html",
    styleUrl: "./modal-examples-page.component.css",
})
export class ModalExamplesPageComponent {
    public readonly examples = {
        defaults: {
            html: modalDefaultHtml,
            typescript: modalDefaultTs,
        },
        componentContent: {
            html: `<!-- modal-component-content.component.html -->\n${modalComponentContentHtml}\n\n<!-- modal-demo-content.component.html -->\n${modalDemoContentHtml}`,
            typescript: `${modalComponentContentTs}\n\n// modal-demo-content.component.ts\n${modalDemoContentTs}`,
        },
        focus: {
            html: `<!-- modal-focus.component.html -->\n${modalFocusHtml}\n\n<!-- modal-focus-content.component.html -->\n${modalFocusContentHtml}`,
            typescript: `${modalFocusTs}\n\n// modal-focus-content.component.ts\n${modalFocusContentTs}`,
        },
        options: {
            html: modalOptionsHtml,
            typescript: modalOptionsTs,
            css: modalOptionsCss,
        },
        updatable: {
            html: `<!-- modal-updatable.component.html -->\n${modalUpdatableHtml}\n\n<!-- modal-updatable-content.component.html -->\n${modalUpdatableContentHtml}`,
            typescript: `${modalUpdatableTs}\n\n// modal-updatable-content.component.ts\n${modalUpdatableContentTs}`,
            css: modalOptionsCss,
        },
        stacked: {
            html: `<!-- modal-stacked.component.html -->\n${modalStackedHtml}\n\n<!-- modal-stacked-content.component.html -->\n${modalStackedContentHtml}`,
            typescript: `${modalStackedTs}\n\n// modal-stacked-content.component.ts\n${modalStackedContentTs}`,
        },
        global: {
            html: modalGlobalHtml,
            typescript: modalGlobalTs,
        },
    }
}
