import { Component } from "ngjs-core";
const serviceTs = "import { Component, ElementRef, type OnDestroy } from \"ngjs-core\";\nimport { NgbScrollSpyService } from \"ngb-js/scrollspy\";\n\n@Component({\n    selector: \"docs-scrollspy-service-demo\",\n    controllerAs: \"example\",\n    templateUrl: \"./scrollspy-service-demo.component.html\",\n    styleUrl: \"./scrollspy-service-demo.component.css\",\n    providers: [NgbScrollSpyService],\n})\nexport class ScrollspyServiceDemoComponent implements OnDestroy {\n    public readonly fragments = [\"service-introduction\", \"service-options\", \"service-finish\"];\n    public running = false;\n    public observingFinish = true;\n    private root?: HTMLElement;\n\n    constructor(\n        private readonly elementRef: ElementRef<HTMLElement>,\n        public readonly scrollSpy: NgbScrollSpyService,\n    ) {}\n\n    public ngAfterViewInit(): void {\n        this.root = this.elementRef.nativeElement.querySelector<HTMLElement>(\"[data-service-scrollspy]\") ?? undefined;\n        this.start();\n    }\n\n    public ngOnDestroy(): void {\n        this.scrollSpy.stop();\n    }\n\n    public start(): void {\n        if (!this.root) return;\n        this.scrollSpy.start({\n            root: this.root,\n            fragments: this.fragments,\n            rootMargin: \"0px 0px -45%\",\n        });\n        this.running = true;\n        this.observingFinish = true;\n    }\n\n    public stop(): void {\n        this.scrollSpy.stop();\n        this.running = false;\n    }\n\n    public toggleFinish(): void {\n        if (this.observingFinish) {\n            this.scrollSpy.unobserve(\"service-finish\");\n        } else {\n            this.scrollSpy.observe(\"service-finish\");\n        }\n        this.observingFinish = !this.observingFinish;\n    }\n}\n";
const serviceHtml = "<div class=\"d-flex flex-wrap align-items-center gap-2 mb-3\">\n    <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.start()\" disabled=\"example.running\">Start</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\" ng-click=\"example.stop()\" disabled=\"!example.running\">Stop</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\" ng-click=\"example.toggleFinish()\" disabled=\"!example.running\">\n        {{ example.observingFinish ? 'Unobserve' : 'Observe' }} finish\n    </button>\n    <span class=\"small text-body-secondary ms-sm-auto\">\n        Active: <code>{{ example.scrollSpy.active || 'none' }}</code>\n    </span>\n</div>\n\n<div class=\"row g-3\">\n    <div class=\"col-md-4\">\n        <div class=\"nav nav-pills flex-column\">\n            <button type=\"button\" class=\"nav-link text-start\" ng-click=\"example.scrollSpy.scrollTo('service-introduction')\">Introduction</button>\n            <button type=\"button\" class=\"nav-link text-start\" ng-click=\"example.scrollSpy.scrollTo('service-options')\">Options</button>\n            <button type=\"button\" class=\"nav-link text-start\" ng-click=\"example.scrollSpy.scrollTo('service-finish')\">Finish</button>\n        </div>\n    </div>\n\n    <div class=\"col-md-8\">\n        <div class=\"bg-body-tertiary border rounded p-3 overflow-y-auto\" style=\"height: 17rem\" data-service-scrollspy>\n            <section id=\"service-introduction\" class=\"pb-5\">\n                <h3 class=\"h5\">Introduction</h3>\n                <p>The service can observe ordinary DOM elements without scrollspy directives.</p>\n            </section>\n            <section id=\"service-options\" class=\"pb-5\">\n                <h3 class=\"h5\">Options</h3>\n                <p>Call <code>start()</code> with a root element and the fragment ids to observe.</p>\n            </section>\n            <section id=\"service-finish\" class=\"pb-5 mb-5\">\n                <h3 class=\"h5\">Finish</h3>\n                <p class=\"mb-5\"><code>observe()</code>, <code>unobserve()</code>, <code>scrollTo()</code> and <code>stop()</code> remain available programmatically.</p>\n            </section>\n        </div>\n    </div>\n</div>\n";
const basicHtml = "<div\n    class=\"bg-body-tertiary border rounded p-3 mb-3\"\n    style=\"height: 14rem\"\n    ngb-scroll-spy\n    root-margin=\"0px 0px -45%\"\n    ng-ref=\"example.spy\"\n    ng-ref-read=\"ngbScrollSpy\">\n    <section class=\"pb-5\" ngb-scroll-spy-fragment=\"basic-scrollspy-first\">\n        <h3 class=\"h5\">First heading</h3>\n        <p>Scrollspy observes each registered fragment and keeps track of the section currently crossing the viewport.</p>\n    </section>\n    <section class=\"pb-5\" ngb-scroll-spy-fragment=\"basic-scrollspy-second\">\n        <h3 class=\"h5\">Second heading</h3>\n        <p>The scroll container is the element carrying the <code>ngb-scroll-spy</code> directive.</p>\n    </section>\n    <section class=\"pb-5 mb-5\" ngb-scroll-spy-fragment=\"basic-scrollspy-third\">\n        <h3 class=\"h5\">Third heading</h3>\n        <p class=\"mb-5\">Every fragment gets its DOM id from <code>ngb-scroll-spy-fragment</code>.</p>\n    </section>\n</div>\n\n<p class=\"small text-body-secondary mb-0\">\n    Active fragment: <code>{{ example.spy.active || 'none' }}</code>\n</p>\n";
const navbarHtml = "<div class=\"d-flex flex-column\">\n    <div\n        class=\"bg-body-tertiary border rounded p-3 order-2\"\n        style=\"height: 15rem\"\n        ngb-scroll-spy\n        root-margin=\"0px 0px -45%\"\n        ng-ref=\"example.spy\"\n        ng-ref-read=\"ngbScrollSpy\">\n        <section class=\"pb-5\" ngb-scroll-spy-fragment=\"navbar-overview\">\n            <h3 class=\"h5\">Overview</h3>\n            <p>The menu can live outside the observed container when it receives an explicit scrollspy reference.</p>\n        </section>\n        <section class=\"pb-5\" ngb-scroll-spy-fragment=\"navbar-features\">\n            <h3 class=\"h5\">Features</h3>\n            <p>Bootstrap navbar and nav utilities provide the layout while ngb-js manages navigation state.</p>\n        </section>\n        <section class=\"pb-5 mb-5\" ngb-scroll-spy-fragment=\"navbar-summary\">\n            <h3 class=\"h5\">Summary</h3>\n            <p class=\"mb-5\">Selecting a navbar item scrolls this container without moving the surrounding page.</p>\n        </section>\n    </div>\n\n    <nav class=\"navbar bg-body-tertiary border rounded px-3 mb-3 order-1\">\n        <span class=\"navbar-brand mb-0 h1\">Docs</span>\n        <div class=\"nav nav-pills\" ngb-scroll-spy-menu=\"example.spy\">\n            <button type=\"button\" class=\"nav-link\" ngb-scroll-spy-item=\"navbar-overview\">Overview</button>\n            <button type=\"button\" class=\"nav-link\" ngb-scroll-spy-item=\"navbar-features\">Features</button>\n            <button type=\"button\" class=\"nav-link\" ngb-scroll-spy-item=\"navbar-summary\">Summary</button>\n        </div>\n    </nav>\n</div>\n";
const nestedHtml = "<div class=\"row g-3\">\n    <div class=\"col-md-8 order-2\">\n        <div\n            class=\"bg-body-tertiary border rounded p-3\"\n            style=\"height: 18rem\"\n            ngb-scroll-spy\n            root-margin=\"0px 0px -45%\"\n            ng-ref=\"example.spy\"\n            ng-ref-read=\"ngbScrollSpy\">\n            <section class=\"pb-4\" ngb-scroll-spy-fragment=\"nested-guide\">\n                <h3 class=\"h4\">Guide</h3>\n                <p>A parent item can represent a complete group of related sections.</p>\n            </section>\n            <section class=\"pb-5\" ngb-scroll-spy-fragment=\"nested-install\">\n                <h4 class=\"h5\">Install</h4>\n                <p>Child items use <code>parent</code> to activate both their own entry and the group entry.</p>\n            </section>\n            <section class=\"pb-5\" ngb-scroll-spy-fragment=\"nested-configure\">\n                <h4 class=\"h5\">Configure</h4>\n                <p>The menu directive coordinates the active state across every descendant item.</p>\n            </section>\n            <section class=\"pb-5 mb-5\" ngb-scroll-spy-fragment=\"nested-reference\">\n                <h3 class=\"h4\">Reference</h3>\n                <p class=\"mb-5\">Top-level entries continue to work alongside nested groups.</p>\n            </section>\n        </div>\n    </div>\n\n    <div class=\"col-md-4 order-1\">\n        <nav class=\"nav nav-pills flex-column\" ngb-scroll-spy-menu=\"example.spy\" aria-label=\"Nested example navigation\">\n            <button type=\"button\" class=\"nav-link text-start\" ngb-scroll-spy-item=\"nested-guide\">Guide</button>\n            <nav class=\"nav nav-pills flex-column ms-3\">\n                <button type=\"button\" class=\"nav-link text-start my-1\" ngb-scroll-spy-item=\"nested-install\" parent=\"nested-guide\">Install</button>\n                <button type=\"button\" class=\"nav-link text-start my-1\" ngb-scroll-spy-item=\"nested-configure\" parent=\"nested-guide\">Configure</button>\n            </nav>\n            <button type=\"button\" class=\"nav-link text-start\" ngb-scroll-spy-item=\"nested-reference\">Reference</button>\n        </nav>\n    </div>\n</div>\n";
const menuItemsHtml = "<div class=\"row g-3\">\n    <div class=\"col-md-8 order-2\">\n        <div\n            class=\"bg-body-tertiary border rounded p-3\"\n            style=\"height: 16rem\"\n            ngb-scroll-spy\n            root-margin=\"0px 0px -45%\"\n            ng-ref=\"example.spy\"\n            ng-ref-read=\"ngbScrollSpy\">\n            <section class=\"pb-5\" ngb-scroll-spy-fragment=\"menu-items-first\">\n                <h3 class=\"h5\">First section</h3>\n                <p>Clicking an item asks the referenced scrollspy to move to its matching fragment.</p>\n            </section>\n            <section class=\"pb-5\" ngb-scroll-spy-fragment=\"menu-items-second\">\n                <h3 class=\"h5\">Second section</h3>\n                <p>The active item receives Bootstrap's <code>active</code> class automatically.</p>\n            </section>\n            <section class=\"pb-5 mb-5\" ngb-scroll-spy-fragment=\"menu-items-third\">\n                <h3 class=\"h5\">Third section</h3>\n                <p class=\"mb-5\">Items can be buttons or links; their fragment identifier is the important part.</p>\n            </section>\n        </div>\n    </div>\n\n    <div class=\"col-md-4 order-1\">\n        <div class=\"list-group\" ngb-scroll-spy-menu=\"example.spy\">\n            <button type=\"button\" class=\"list-group-item list-group-item-action\" ngb-scroll-spy-item=\"menu-items-first\">First</button>\n            <button type=\"button\" class=\"list-group-item list-group-item-action\" ngb-scroll-spy-item=\"menu-items-second\">Second</button>\n            <a role=\"button\" class=\"list-group-item list-group-item-action\" ngb-scroll-spy-item=\"menu-items-third\">Third</a>\n        </div>\n    </div>\n</div>\n";

@Component({
    selector: "docs-scrollspy-examples-page",
    controllerAs: "$",
    templateUrl: "./scrollspy-examples-page.component.html",
    styleUrl: "./scrollspy-examples-page.component.css",
})
export class ScrollspyExamplesPageComponent {
    public readonly examples = {
        basic: { html: basicHtml },
        menuItems: { html: menuItemsHtml },
        nested: { html: nestedHtml },
        navbar: { html: navbarHtml },
        service: { html: serviceHtml, typescript: serviceTs },
    }
}
