import { Component } from "ngjs-core";
const contextualTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-contextual-text-progressbar\",\n    controllerAs: \"example\",\n    templateUrl: \"./contextual-text-progressbar.component.html\",\n    styleUrl: \"./contextual-text-progressbar.component.css\",\n})\nexport class ContextualTextProgressbarComponent {}\n";
const contextualHtml = "<div class=\"vstack gap-3\">\n    <ngb-progressbar type=\"success\" text-type=\"white\" value=\"25\" show-value=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"dark\" text-type=\"white\" value=\"50\" show-value=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"light\" text-type=\"success\" value=\"75\" show-value=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"warning\" text-type=\"dark\" value=\"100\" show-value=\"true\"></ngb-progressbar>\n</div>\n";
const globalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbProgressbarConfig } from \"ngb-js/progressbar\";\n\n@Component({\n    selector: \"docs-progressbar-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./progressbar-global.component.html\",\n    styleUrl: \"./progressbar-global.component.css\",\n})\nexport class ProgressbarGlobalComponent implements AfterViewInit, OnDestroy {\n    private readonly initialConfig: Pick<NgbProgressbarConfig, \"animated\" | \"height\" | \"max\" | \"showValue\" | \"striped\" | \"textType\" | \"type\">;\n\n    constructor(private readonly config: NgbProgressbarConfig) {\n        this.initialConfig = {\n            animated: config.animated,\n            height: config.height,\n            max: config.max,\n            showValue: config.showValue,\n            striped: config.striped,\n            textType: config.textType,\n            type: config.type,\n        };\n        config.animated = true;\n        config.height = \"1.5rem\";\n        config.max = 200;\n        config.showValue = true;\n        config.striped = true;\n        config.textType = \"light\";\n        config.type = \"primary\";\n    }\n\n    public ngAfterViewInit() { this.restoreConfig(); }\n    public ngOnDestroy() { this.restoreConfig(); }\n    private restoreConfig() { Object.assign(this.config, this.initialConfig); }\n}\n";
const globalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div><p class=\"fw-semibold mb-1\">Global defaults used by this example</p><p class=\"small text-body-secondary mb-0\">Primary, striped and animated; maximum 200, visible percentage and 1.5rem height.</p></div>\n</div>\n\n<ngb-progressbar value=\"135\"></ngb-progressbar>\n";
const heightTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-progress-height\",\n    controllerAs: \"example\",\n    templateUrl: \"./progress-height.component.html\",\n    styleUrl: \"./progress-height.component.css\",\n})\nexport class ProgressHeightComponent {}\n";
const heightHtml = "<div class=\"vstack gap-3\">\n    <ngb-progressbar type=\"success\" value=\"25\">Default</ngb-progressbar>\n    <ngb-progressbar type=\"info\" value=\"50\" height=\"'10px'\">10px</ngb-progressbar>\n    <ngb-progressbar type=\"warning\" value=\"75\" height=\"'1.5rem'\">1.5rem</ngb-progressbar>\n    <ngb-progressbar type=\"danger\" value=\"100\" height=\"'2rem'\">2rem</ngb-progressbar>\n</div>\n";
const labelsTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-custom-labels-progressbar\",\n    controllerAs: \"example\",\n    templateUrl: \"./custom-labels-progressbar.component.html\",\n    styleUrl: \"./custom-labels-progressbar.component.css\",\n})\nexport class CustomLabelsProgressbarComponent {}\n";
const labelsHtml = "<div class=\"vstack gap-3\">\n    <ngb-progressbar type=\"success\" value=\"25\"><strong>25%</strong></ngb-progressbar>\n    <ngb-progressbar type=\"info\" value=\"50\">Copying file <strong class=\"ms-1\">2 of 4</strong></ngb-progressbar>\n    <ngb-progressbar type=\"warning\" value=\"75\" striped=\"true\" animated=\"true\"><em>Almost there…</em></ngb-progressbar>\n    <ngb-progressbar type=\"danger\" value=\"100\">Completed!</ngb-progressbar>\n</div>\n";
const simpleTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-simple-progressbar\",\n    controllerAs: \"example\",\n    templateUrl: \"./simple-progressbar.component.html\",\n    styleUrl: \"./simple-progressbar.component.css\",\n})\nexport class SimpleProgressbarComponent {}\n";
const simpleHtml = "<div class=\"vstack gap-3\">\n    <ngb-progressbar type=\"success\" value=\"25\"></ngb-progressbar>\n    <ngb-progressbar type=\"info\" value=\"50\"></ngb-progressbar>\n    <ngb-progressbar type=\"warning\" value=\"75\"></ngb-progressbar>\n    <ngb-progressbar type=\"danger\" value=\"100\"></ngb-progressbar>\n    <ngb-progressbar type=\"primary\" value=\"75\"></ngb-progressbar>\n    <ngb-progressbar type=\"secondary\" value=\"50\"></ngb-progressbar>\n    <ngb-progressbar type=\"dark\" value=\"25\"></ngb-progressbar>\n</div>\n";
const stackedTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-progress-bars-stacked\",\n    controllerAs: \"example\",\n    templateUrl: \"./progress-bars-stacked.component.html\",\n    styleUrl: \"./progress-bars-stacked.component.css\",\n})\nexport class ProgressBarsStackedComponent {}\n";
const stackedHtml = "<ngb-progressbar-stacked>\n    <ngb-progressbar type=\"danger\" value=\"20\">20%</ngb-progressbar>\n    <ngb-progressbar type=\"warning\" value=\"35\">35%</ngb-progressbar>\n    <ngb-progressbar type=\"success\" value=\"45\">45%</ngb-progressbar>\n</ngb-progressbar-stacked>\n\n<p class=\"small text-body-secondary mt-3 mb-0\">The three segments share one Bootstrap stacked progress container.</p>\n";
const stripedTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-striped-progress-bar\",\n    controllerAs: \"example\",\n    templateUrl: \"./striped-progress-bar.component.html\",\n    styleUrl: \"./striped-progress-bar.component.css\",\n})\nexport class StripedProgressBarComponent {}\n";
const stripedHtml = "<div class=\"vstack gap-3\">\n    <ngb-progressbar type=\"success\" value=\"25\" striped=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"info\" value=\"50\" striped=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"warning\" value=\"75\" striped=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"danger\" value=\"100\" striped=\"true\"></ngb-progressbar>\n    <ngb-progressbar type=\"primary\" value=\"65\" striped=\"true\" animated=\"true\">Animated</ngb-progressbar>\n</div>\n";

@Component({
    selector: "docs-progressbar-examples-page",
    controllerAs: "$",
    templateUrl: "./progressbar-examples-page.component.html",
    styleUrl: "./progressbar-examples-page.component.css",
})
export class ProgressbarExamplesPageComponent {
    public readonly examples = {
        simple: { html: simpleHtml, typescript: simpleTs },
        contextual: { html: contextualHtml, typescript: contextualTs },
        striped: { html: stripedHtml, typescript: stripedTs },
        labels: { html: labelsHtml, typescript: labelsTs },
        height: { html: heightHtml, typescript: heightTs },
        stacked: { html: stackedHtml, typescript: stackedTs },
        global: { html: globalHtml, typescript: globalTs },
    }
}
