import { Component } from "ngjs-core";
const exactHtml = "<label class=\"form-label\" for=\"exact-typeahead\">Search for a state</label>\n<input id=\"exact-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" input-formatter=\"example.formatter\" result-formatter=\"example.formatter\" select-on-exact=\"true\" placeholder=\"Try California\">\n<pre class=\"mt-3 mb-0\">Model: {{ example.model | json }}</pre>\n";
const exactTs = "import { Component } from \"ngjs-core\";\nimport { debounceTime, map, type OperatorFunction } from \"rxjs\";\n\ninterface State { name: string }\nconst STATES: State[] = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\"].map(name => ({ name }));\n\n@Component({\n    selector: \"docs-exact-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./exact-typeahead.component.html\",\n    styleUrl: \"./exact-typeahead.component.css\",\n})\nexport class ExactTypeaheadComponent {\n    public model?: State;\n    public readonly formatter = (state: State): string => state.name;\n    public readonly search: OperatorFunction<string, State[]> = text$ => text$.pipe(\n        debounceTime(200),\n        map(term => term ? STATES.filter(state => state.name.toLowerCase().includes(term.toLowerCase())) : []),\n    );\n}\n";
const focusHtml = "<label class=\"form-label\" for=\"focus-typeahead\">Search for a state</label>\n<input id=\"focus-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" ng-focus=\"example.focus$.next($event.target.value)\" placeholder=\"Focus to see suggestions\">\n<p class=\"small text-body-secondary mt-2 mb-0\">Model: <strong>{{ example.model || 'empty' }}</strong></p>\n";
const focusTs = "import { Component, type OnDestroy } from \"ngjs-core\";\nimport { debounceTime, distinctUntilChanged, map, merge, type OperatorFunction, Subject } from \"rxjs\";\n\nconst STATES = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\", \"Idaho\", \"Illinois\", \"Indiana\", \"Iowa\", \"Kansas\", \"Kentucky\", \"Louisiana\", \"Maine\", \"Maryland\", \"Massachusetts\", \"Michigan\", \"Minnesota\", \"Mississippi\", \"Missouri\", \"Montana\", \"Nebraska\", \"Nevada\", \"New Hampshire\", \"New Jersey\", \"New Mexico\", \"New York\", \"North Carolina\", \"North Dakota\", \"Ohio\", \"Oklahoma\", \"Oregon\", \"Pennsylvania\", \"Rhode Island\", \"South Carolina\", \"South Dakota\", \"Tennessee\", \"Texas\", \"Utah\", \"Vermont\", \"Virginia\", \"Washington\", \"West Virginia\", \"Wisconsin\", \"Wyoming\"];\n\n@Component({\n    selector: \"docs-focus-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./focus-typeahead.component.html\",\n    styleUrl: \"./focus-typeahead.component.css\",\n})\nexport class FocusTypeaheadComponent implements OnDestroy {\n    public model = \"\";\n    public readonly focus$ = new Subject<string>();\n    public readonly search: OperatorFunction<string, string[]> = text$ => merge(\n        text$.pipe(debounceTime(200), distinctUntilChanged()),\n        this.focus$,\n    ).pipe(\n        map(term => (term ? STATES.filter(state => state.toLowerCase().includes(term.toLowerCase())) : STATES).slice(0, 10)),\n    );\n    public ngOnDestroy(): void { this.focus$.complete(); }\n}\n";
const formattedHtml = "<label class=\"form-label\" for=\"formatted-typeahead\">Search for a state</label>\n<input id=\"formatted-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" result-formatter=\"example.formatter\" placeholder=\"Results are formatted in uppercase\">\n<p class=\"small text-body-secondary mt-2 mb-0\">Model: <strong>{{ example.model || 'empty' }}</strong></p>\n";
const formattedTs = "import { Component } from \"ngjs-core\";\nimport { debounceTime, distinctUntilChanged, map, type OperatorFunction } from \"rxjs\";\n\nconst STATES = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\"];\n\n@Component({\n    selector: \"docs-formatted-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./formatted-typeahead.component.html\",\n    styleUrl: \"./formatted-typeahead.component.css\",\n})\nexport class FormattedTypeaheadComponent {\n    public model = \"\";\n    public readonly formatter = (result: string): string => result.toUpperCase();\n    public readonly search: OperatorFunction<string, string[]> = text$ => text$.pipe(\n        debounceTime(200),\n        distinctUntilChanged(),\n        map(term => term ? STATES.filter(state => state.toLowerCase().includes(term.toLowerCase())) : []),\n    );\n}\n";
const globalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">Hint completion, exact-match selection and a popup appended to body.</p>\n    </div>\n</div>\n\n<label class=\"form-label\" for=\"global-typeahead\">Search for a state</label>\n<input id=\"global-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" placeholder=\"Try Cal\">\n";
const globalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbTypeaheadConfig } from \"ngb-js/typeahead\";\nimport { debounceTime, distinctUntilChanged, map, type OperatorFunction } from \"rxjs\";\n\nconst STATES = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\"];\n\n@Component({\n    selector: \"docs-typeahead-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./typeahead-global.component.html\",\n    styleUrl: \"./typeahead-global.component.css\",\n})\nexport class TypeaheadGlobalComponent implements AfterViewInit, OnDestroy {\n    public model = \"\";\n    private readonly initialConfig: Pick<NgbTypeaheadConfig, \"container\" | \"selectOnExact\" | \"showHint\">;\n\n    constructor(private readonly config: NgbTypeaheadConfig) {\n        this.initialConfig = {\n            container: config.container,\n            selectOnExact: config.selectOnExact,\n            showHint: config.showHint,\n        };\n        config.container = \"body\";\n        config.selectOnExact = true;\n        config.showHint = true;\n    }\n\n    public readonly search: OperatorFunction<string, string[]> = text$ => text$.pipe(\n        debounceTime(200),\n        distinctUntilChanged(),\n        map(term => term.length < 2 ? [] : STATES.filter(state => state.toLowerCase().startsWith(term.toLowerCase()))),\n    );\n\n    public ngAfterViewInit(): void { this.restoreConfig(); }\n    public ngOnDestroy(): void { this.restoreConfig(); }\n    private restoreConfig(): void {\n        this.config.container = this.initialConfig.container;\n        this.config.selectOnExact = this.initialConfig.selectOnExact;\n        this.config.showHint = this.initialConfig.showHint;\n    }\n}\n";
const nonEditableHtml = "<p>Manual text is not accepted; the model changes only after selecting a suggestion.</p>\n<label class=\"form-label\" for=\"non-editable-typeahead\">Search for a state</label>\n<input id=\"non-editable-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" input-formatter=\"example.formatter\" result-formatter=\"example.formatter\" editable=\"false\" placeholder=\"Type at least two characters\">\n<pre class=\"mt-3 mb-0\">Model: {{ example.model | json }}</pre>\n";
const nonEditableTs = "import { Component } from \"ngjs-core\";\nimport { debounceTime, distinctUntilChanged, map, type OperatorFunction } from \"rxjs\";\n\ninterface State { id: number; name: string }\nconst STATES: State[] = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\"].map((name, id) => ({ id, name }));\n\n@Component({\n    selector: \"docs-non-editable-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./non-editable-typeahead.component.html\",\n    styleUrl: \"./non-editable-typeahead.component.css\",\n})\nexport class NonEditableTypeaheadComponent {\n    public model: State | null = null;\n    public readonly formatter = (state: State): string => state.name;\n    public readonly search: OperatorFunction<string, State[]> = text$ => text$.pipe(\n        debounceTime(200),\n        distinctUntilChanged(),\n        map(term => term.length < 2 ? [] : STATES.filter(state => state.name.toLowerCase().includes(term.toLowerCase()))),\n    );\n}\n";
const simpleHtml = "<label class=\"form-label\" for=\"simple-typeahead\">Search for a state</label>\n<input id=\"simple-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" placeholder=\"Type at least two characters\">\n<p class=\"small text-body-secondary mt-2 mb-0\">Model: <strong>{{ example.model || 'empty' }}</strong></p>\n";
const simpleTs = "import { Component } from \"ngjs-core\";\nimport { debounceTime, distinctUntilChanged, map, type OperatorFunction } from \"rxjs\";\n\nconst STATES = [\"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"Colorado\", \"Connecticut\", \"Delaware\", \"Florida\", \"Georgia\", \"Hawaii\", \"Idaho\", \"Illinois\", \"Indiana\", \"Iowa\", \"Kansas\", \"Kentucky\", \"Louisiana\", \"Maine\", \"Maryland\", \"Massachusetts\", \"Michigan\", \"Minnesota\", \"Mississippi\", \"Missouri\", \"Montana\", \"Nebraska\", \"Nevada\", \"New Hampshire\", \"New Jersey\", \"New Mexico\", \"New York\", \"North Carolina\", \"North Dakota\", \"Ohio\", \"Oklahoma\", \"Oregon\", \"Pennsylvania\", \"Rhode Island\", \"South Carolina\", \"South Dakota\", \"Tennessee\", \"Texas\", \"Utah\", \"Vermont\", \"Virginia\", \"Washington\", \"West Virginia\", \"Wisconsin\", \"Wyoming\"];\n\n@Component({\n    selector: \"docs-simple-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./simple-typeahead.component.html\",\n    styleUrl: \"./simple-typeahead.component.css\",\n})\nexport class SimpleTypeaheadComponent {\n    public model = \"\";\n    public readonly search: OperatorFunction<string, string[]> = text$ => text$.pipe(\n        debounceTime(200),\n        distinctUntilChanged(),\n        map(term => term.length < 2 ? [] : STATES.filter(state => state.toLowerCase().includes(term.toLowerCase())).slice(0, 10)),\n    );\n}\n";
const templateResultsHtml = "<ng-template ng-ref=\"example.resultTemplate\" let-result=\"result\" let-term=\"term\">\n    <span class=\"d-flex align-items-center gap-2\">\n        <span class=\"fs-5\" aria-hidden=\"true\">{{ result.flag }}</span>\n        <span class=\"flex-grow-1\"><ngb-highlight result=\"result.name\" term=\"term\"></ngb-highlight></span>\n        <small class=\"text-body-secondary\">{{ result.region }}</small>\n    </span>\n</ng-template>\n\n<label class=\"form-label\" for=\"template-results-typeahead\">Search for a country</label>\n<input id=\"template-results-typeahead\" type=\"text\" class=\"form-control\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" result-template=\"example.resultTemplate\" input-formatter=\"example.formatter\" placeholder=\"Try Mexico\">\n<pre class=\"mt-3 mb-0\">Model: {{ example.model | json }}</pre>\n";
const templateResultsTs = "import { Component, type TemplateRef } from \"ngjs-core\";\nimport { debounceTime, map, type OperatorFunction } from \"rxjs\";\n\ninterface Country { name: string; flag: string; region: string }\nconst COUNTRIES: Country[] = [\n    { name: \"Mexico\", flag: \"🇲🇽\", region: \"North America\" },\n    { name: \"Argentina\", flag: \"🇦🇷\", region: \"South America\" },\n    { name: \"Brazil\", flag: \"🇧🇷\", region: \"South America\" },\n    { name: \"Canada\", flag: \"🇨🇦\", region: \"North America\" },\n    { name: \"Colombia\", flag: \"🇨🇴\", region: \"South America\" },\n    { name: \"Germany\", flag: \"🇩🇪\", region: \"Europe\" },\n    { name: \"Japan\", flag: \"🇯🇵\", region: \"Asia\" },\n    { name: \"Spain\", flag: \"🇪🇸\", region: \"Europe\" },\n];\n\n@Component({\n    selector: \"docs-template-results-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./template-results-typeahead.component.html\",\n    styleUrl: \"./template-results-typeahead.component.css\",\n})\nexport class TemplateResultsTypeaheadComponent {\n    public model?: Country;\n    public resultTemplate?: TemplateRef<unknown>;\n    public readonly formatter = (country: Country): string => country.name;\n    public readonly search: OperatorFunction<string, Country[]> = text$ => text$.pipe(\n        debounceTime(200),\n        map(term => term ? COUNTRIES.filter(country => country.name.toLowerCase().includes(term.toLowerCase())).slice(0, 8) : []),\n    );\n}\n";
const wikipediaHtml = "<label class=\"form-label\" for=\"wikipedia-typeahead\">Search for a Wikipedia page</label>\n<input id=\"wikipedia-typeahead\" type=\"text\" class=\"form-control\" ng-class=\"{ 'is-invalid': example.searchFailed }\" ng-model=\"example.model\" ngb-typeahead=\"example.search\" placeholder=\"Wikipedia search\">\n<div class=\"form-text\" ng-if=\"example.searching\">Searching…</div>\n<div class=\"invalid-feedback\" ng-if=\"example.searchFailed\">Suggestions could not be loaded.</div>\n<p class=\"small text-body-secondary mt-2 mb-0\">Model: <strong>{{ example.model || 'empty' }}</strong></p>\n";
const wikipediaTs = "import { Component, Injectable } from \"ngjs-core\";\nimport { HttpClient, HttpParams } from \"ngjs-core/common/http\";\nimport { catchError, debounceTime, distinctUntilChanged, map, type OperatorFunction, of, switchMap, tap } from \"rxjs\";\n\nconst WIKI_URL = \"https://en.wikipedia.org/w/api.php\";\ntype WikiResponse = [string, string[], string[], string[]];\n\n@Injectable()\nexport class WikipediaSearchService {\n    constructor(private readonly http: HttpClient) {}\n\n    public search(term: string) {\n        if (!term) return of([] as string[]);\n        return this.http.get<WikiResponse>(WIKI_URL, {\n            params: new HttpParams({ fromObject: { action: \"opensearch\", format: \"json\", origin: \"*\", search: term } }),\n        }).pipe(map(response => response[1]));\n    }\n}\n\n@Component({\n    selector: \"docs-wikipedia-typeahead\",\n    controllerAs: \"example\",\n    templateUrl: \"./wikipedia-typeahead.component.html\",\n    styleUrl: \"./wikipedia-typeahead.component.css\",\n})\nexport class WikipediaTypeaheadComponent {\n    public model = \"\";\n    public searching = false;\n    public searchFailed = false;\n\n    constructor(private readonly wikipedia: WikipediaSearchService) {}\n\n    public readonly search: OperatorFunction<string, string[]> = text$ => text$.pipe(\n        debounceTime(300),\n        distinctUntilChanged(),\n        tap(() => this.searching = true),\n        switchMap(term => this.wikipedia.search(term).pipe(\n            tap(() => this.searchFailed = false),\n            catchError(() => {\n                this.searchFailed = true;\n                return of([] as string[]);\n            }),\n        )),\n        tap(() => this.searching = false),\n    );\n}\n";

@Component({
    selector: "docs-typeahead-examples-page",
    controllerAs: "$",
    templateUrl: "./typeahead-examples-page.component.html",
    styleUrl: "./typeahead-examples-page.component.css",
})
export class TypeaheadExamplesPageComponent {
    public readonly examples = {
        simple: { html: simpleHtml, typescript: simpleTs },
        focus: { html: focusHtml, typescript: focusTs },
        formatted: { html: formattedHtml, typescript: formattedTs },
        exact: { html: exactHtml, typescript: exactTs },
        wikipedia: { html: wikipediaHtml, typescript: wikipediaTs },
        templateResults: { html: templateResultsHtml, typescript: templateResultsTs },
        nonEditable: { html: nonEditableHtml, typescript: nonEditableTs },
        global: { html: globalHtml, typescript: globalTs },
    }
}
