import { Component } from "ngjs-core";
const autocloseHtml = "<ng-template ng-ref=\"example.contentTemplate\">\n    <button type=\"button\" class=\"btn btn-sm btn-light\">Click inside</button>\n</ng-template>\n\n<p>Every tooltip can also be closed with <kbd>Esc</kbd>.</p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" triggers=\"click\" auto-close=\"'inside'\" ngb-tooltip=\"example.contentTemplate\">Inside clicks</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" triggers=\"click\" auto-close=\"'outside'\" ngb-tooltip=\"example.contentTemplate\">Outside clicks</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" triggers=\"click\" auto-close=\"true\" ngb-tooltip=\"example.contentTemplate\">All clicks</button>\n</div>\n";
const autocloseTs = "import { Component, type TemplateRef } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-autoclose\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-autoclose.component.html\",\n    styleUrl: \"./tooltip-autoclose.component.css\",\n})\nexport class TooltipAutocloseComponent {\n    public contentTemplate?: TemplateRef<unknown>;\n}\n";
const bodyHtml = "<div class=\"overflow-hidden border rounded p-4\" style=\"max-width: 24rem\">\n    <p class=\"small text-body-secondary\">This container clips overflowing descendants.</p>\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"top\" ngb-tooltip=\"'Inserted next to the trigger.'\">Default</button>\n        <button type=\"button\" class=\"btn btn-outline-primary\" placement=\"top\" ngb-tooltip=\"'Appended directly to document.body.'\" container=\"body\">Append to body</button>\n    </div>\n</div>\n";
const bodyTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-body\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-body.component.html\",\n    styleUrl: \"./tooltip-body.component.css\",\n})\nexport class TooltipBodyComponent {}\n";
const contextHtml = "<ng-template ng-ref=\"example.contentTemplate\" let-greeting=\"greeting\">{{ greeting }}, <strong>{{ example.name }}</strong>!</ng-template>\n\n<p>Pass a different context each time a tooltip is opened manually.</p>\n<div class=\"d-flex flex-wrap gap-2 mb-4\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"example.contentTemplate\" triggers=\"manual\" ng-ref=\"example.french\" ng-ref-read=\"ngbTooltip\" ng-click=\"example.toggleWithGreeting(example.french, 'Bonjour')\">French</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"example.contentTemplate\" triggers=\"manual\" ng-ref=\"example.german\" ng-ref-read=\"ngbTooltip\" ng-click=\"example.toggleWithGreeting(example.german, 'Guten Tag')\">German</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"example.contentTemplate\" triggers=\"manual\" ng-ref=\"example.english\" ng-ref-read=\"ngbTooltip\" ng-click=\"example.toggleWithGreeting(example.english, 'Hello')\">English</button>\n</div>\n\n<p>Alternatively, provide a default context through <code>tooltip-context</code>.</p>\n<button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"example.contentTemplate\" tooltip-context=\"{ greeting: 'Hola' }\">Spanish</button>\n";
const contextTs = "import { Component, type TemplateRef } from \"ngjs-core\";\nimport type { NgbTooltip } from \"ngb-js/tooltip\";\n\n@Component({\n    selector: \"docs-tooltip-context\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-context.component.html\",\n    styleUrl: \"./tooltip-context.component.css\",\n})\nexport class TooltipContextComponent {\n    public name = \"World\";\n    public contentTemplate?: TemplateRef<unknown>;\n    public french?: NgbTooltip;\n    public german?: NgbTooltip;\n    public english?: NgbTooltip;\n\n    public toggleWithGreeting(tooltip: NgbTooltip, greeting: string): void {\n        tooltip.isOpen() ? tooltip.close() : tooltip.open({ greeting });\n    }\n}\n";
const customClassCss = ".tooltip-custom { --bs-tooltip-bg: var(--bs-primary-bg-subtle); --bs-tooltip-color: var(--bs-primary-text-emphasis); --bs-tooltip-opacity: 1; filter: drop-shadow(0 .35rem .8rem rgba(var(--bs-body-color-rgb), .18)); }\n";
const customClassHtml = "<button type=\"button\" class=\"btn btn-outline-primary\" ngb-tooltip=\"'A custom skin layered on top of Bootstrap tooltip variables.'\" tooltip-class=\"tooltip-custom\">\n    Tooltip with custom class\n</button>\n";
const customClassTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-custom-class\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-custom-class.component.html\",\n    styleUrl: \"./tooltip-custom-class.component.css\",\n})\nexport class TooltipCustomClassComponent {}\n";
const customTargetHtml = "<div class=\"d-flex flex-wrap align-items-baseline gap-2\">\n    <span>You can hover</span>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"'The button triggered me, but the text positioned me.'\" position-target=\"#tooltip-position-target\">this button</button>\n    <span>while the tooltip appears over <strong id=\"tooltip-position-target\" class=\"text-primary\">this target</strong>.</span>\n</div>\n";
const customTargetTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-custom-target\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-custom-target.component.html\",\n    styleUrl: \"./tooltip-custom-target.component.css\",\n})\nexport class TooltipCustomTargetComponent {}\n";
const delaysHtml = "<p>Move the pointer into the tooltip before its close delay expires to keep it open.</p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"'Opens after 300 ms and closes after 500 ms.'\" triggers=\"mouseenter:mouseleave\" open-delay=\"300\" close-delay=\"500\">300 / 500 ms</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ngb-tooltip=\"'Opens after one second and closes after two.'\" triggers=\"mouseenter:mouseleave\" open-delay=\"1000\" close-delay=\"2000\">1 / 2 seconds</button>\n</div>\n";
const delaysTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-delays\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-delays.component.html\",\n    styleUrl: \"./tooltip-delays.component.css\",\n})\nexport class TooltipDelaysComponent {}\n";
const globalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">Hover trigger, end placement, body container and a 300 ms opening delay.</p>\n    </div>\n</div>\n\n<button type=\"button\" class=\"btn btn-outline-primary\" ngb-tooltip=\"'This instance reads every option from NgbTooltipConfig.'\">Hover over me</button>\n";
const globalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbTooltipConfig } from \"ngb-js/tooltip\";\n\n@Component({\n    selector: \"docs-tooltip-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-global.component.html\",\n    styleUrl: \"./tooltip-global.component.css\",\n})\nexport class TooltipGlobalComponent implements AfterViewInit, OnDestroy {\n    private readonly initialConfig: Pick<NgbTooltipConfig, \"container\" | \"openDelay\" | \"placement\" | \"triggers\">;\n\n    constructor(private readonly config: NgbTooltipConfig) {\n        this.initialConfig = {\n            container: config.container,\n            openDelay: config.openDelay,\n            placement: config.placement,\n            triggers: config.triggers,\n        };\n        config.container = \"body\";\n        config.openDelay = 300;\n        config.placement = \"end\";\n        config.triggers = \"mouseenter:mouseleave\";\n    }\n\n    public ngAfterViewInit(): void { this.restoreConfig(); }\n    public ngOnDestroy(): void { this.restoreConfig(); }\n\n    private restoreConfig(): void {\n        this.config.container = this.initialConfig.container;\n        this.config.openDelay = this.initialConfig.openDelay;\n        this.config.placement = this.initialConfig.placement;\n        this.config.triggers = this.initialConfig.triggers;\n    }\n}\n";
const placementsHtml = "<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"top\" ngb-tooltip=\"'Tooltip on top'\">Top</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"end\" ngb-tooltip=\"'Tooltip on right'\">Right</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"bottom\" ngb-tooltip=\"'Tooltip on bottom'\">Bottom</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" placement=\"start\" ngb-tooltip=\"'Tooltip on left'\">Left</button>\n</div>\n";
const placementsTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-placements\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-placements.component.html\",\n    styleUrl: \"./tooltip-placements.component.css\",\n})\nexport class TooltipPlacementsComponent {}\n";
const templateHtml = "<ng-template ng-ref=\"example.contentTemplate\">\n    <span>Hello, <strong>{{ example.name }}</strong>!</span>\n</ng-template>\n\n<div class=\"d-flex flex-wrap align-items-center gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-primary\" ngb-tooltip=\"example.contentTemplate\">HTML and bindings</button>\n    <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\" ng-click=\"example.name = example.name === 'NgbJS' ? 'AngularJS' : 'NgbJS'\">Change binding</button>\n</div>\n";
const templateTs = "import { Component, type TemplateRef } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-tooltip-template\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-template.component.html\",\n    styleUrl: \"./tooltip-template.component.css\",\n})\nexport class TooltipTemplateComponent {\n    public name = \"NgbJS\";\n    public contentTemplate?: TemplateRef<unknown>;\n}\n";
const triggersHtml = "<p class=\"mb-3\">Custom events can be paired as <code>mouseenter:mouseleave</code>.</p>\n<button type=\"button\" class=\"btn btn-outline-secondary mb-4\" ngb-tooltip=\"'Shown while the pointer is over the trigger'\" triggers=\"mouseenter:mouseleave\">Hover over me</button>\n\n<p class=\"mb-3\">Manual triggers delegate opening and closing to application code.</p>\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-primary\" ngb-tooltip=\"'Manually controlled tooltip'\" triggers=\"manual\" auto-close=\"false\" ng-ref=\"example.manual\" ng-ref-read=\"ngbTooltip\" ng-click=\"example.manual.open()\">Open tooltip</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.manual.close()\">Close tooltip</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.manual.toggle()\">Toggle tooltip</button>\n</div>\n";
const triggersTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTooltip } from \"ngb-js/tooltip\";\n\n@Component({\n    selector: \"docs-tooltip-triggers\",\n    controllerAs: \"example\",\n    templateUrl: \"./tooltip-triggers.component.html\",\n    styleUrl: \"./tooltip-triggers.component.css\",\n})\nexport class TooltipTriggersComponent {\n    public manual?: NgbTooltip;\n}\n";

@Component({
    selector: "docs-tooltip-examples-page",
    controllerAs: "$",
    templateUrl: "./tooltip-examples-page.component.html",
    styleUrl: "./tooltip-examples-page.component.css",
})
export class TooltipExamplesPageComponent {
    public readonly examples = {
        placements: { html: placementsHtml, typescript: placementsTs },
        template: { html: templateHtml, typescript: templateTs },
        triggers: { html: triggersHtml, typescript: triggersTs },
        autoclose: { html: autocloseHtml, typescript: autocloseTs },
        context: { html: contextHtml, typescript: contextTs },
        customTarget: { html: customTargetHtml, typescript: customTargetTs },
        delays: { html: delaysHtml, typescript: delaysTs },
        body: { html: bodyHtml, typescript: bodyTs },
        customClass: { html: customClassHtml, typescript: customClassTs, css: customClassCss },
        global: { html: globalHtml, typescript: globalTs },
    }
}
