import { Component } from "ngjs-core";
const adapterTs = "import { Component, type DoCheck } from \"ngjs-core\";\nimport { NgbTimeAdapter, type NgbTimeStruct } from \"ngb-js/timepicker\";\n\nconst pad = (value: number): string => value.toString().padStart(2, \"0\");\n\nexport class NgbTimeStringAdapter extends NgbTimeAdapter<string> {\n    public fromModel(value: string | null): NgbTimeStruct | null {\n        if (!value) return null;\n        const [hour, minute, second] = value.split(\":\").map(Number);\n        return { hour, minute, second };\n    }\n\n    public toModel(time: NgbTimeStruct | null): string | null {\n        return time ? `${pad(time.hour)}:${pad(time.minute)}:${pad(time.second ?? 0)}` : null;\n    }\n}\n\n@Component({\n    selector: \"docs-timepicker-custom-adapter\",\n    controllerAs: \"example\",\n    templateUrl: \"./timepicker-custom-adapter.component.html\",\n    styleUrl: \"./timepicker-custom-adapter.component.css\",\n})\nexport class TimepickerCustomAdapterComponent implements DoCheck {\n    public readonly adapter = new NgbTimeStringAdapter();\n    public time = this.adapter.fromModel(\"13:30:00\");\n    public model = \"13:30:00\";\n\n    public ngDoCheck(): void {\n        this.model = this.adapter.toModel(this.time) ?? \"\";\n    }\n}\n";
const adapterHtml = "<p>This adapter represents the application model as an <code>HH:mm:ss</code> string.</p>\n<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\" seconds=\"true\"></ngb-timepicker>\n    <hr class=\"w-100 my-0\">\n    <pre class=\"w-100 mb-0\">String model: {{ example.model }}</pre>\n</div>\n";
const basicTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-basic-timepicker\",\n    controllerAs: \"example\",\n    templateUrl: \"./basic-timepicker.component.html\",\n    styleUrl: \"./basic-timepicker.component.css\",\n})\nexport class BasicTimepickerComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 0 };\n}\n";
const basicHtml = "<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\"></ngb-timepicker>\n    <hr class=\"w-100 my-0\">\n    <pre class=\"w-100 mb-0\">Selected time: {{ example.time | json }}</pre>\n</div>\n";
const i18nTs = "import { Component, Injectable } from \"ngjs-core\";\nimport { NgbTimepickerI18n, type NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Injectable()\nexport class GreekTimepickerI18n extends NgbTimepickerI18n {\n    public getMorningPeriod(): string { return \"π.μ.\"; }\n    public getAfternoonPeriod(): string { return \"μ.μ.\"; }\n}\n\n@Component({\n    selector: \"docs-timepicker-i18n\",\n    controllerAs: \"example\",\n    templateUrl: \"./timepicker-i18n.component.html\",\n    styleUrl: \"./timepicker-i18n.component.css\",\n    providers: [{ provide: NgbTimepickerI18n, useClass: GreekTimepickerI18n }],\n})\nexport class TimepickerI18nComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 0 };\n    constructor(public readonly i18n: NgbTimepickerI18n) {}\n}\n";
const i18nHtml = "<div class=\"alert alert-light border\" role=\"note\">\n    Greek period labels supplied by a custom <code>NgbTimepickerI18n</code>:\n    <strong>{{ example.i18n.getMorningPeriod() }}</strong> / <strong>{{ example.i18n.getAfternoonPeriod() }}</strong>\n</div>\n\n<div class=\"d-flex align-items-start\">\n    <ngb-timepicker ng-model=\"example.time\" meridian=\"true\"></ngb-timepicker>\n</div>\n";
const meridianTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-meridian-timepicker\",\n    controllerAs: \"example\",\n    templateUrl: \"./meridian-timepicker.component.html\",\n    styleUrl: \"./meridian-timepicker.component.css\",\n})\nexport class MeridianTimepickerComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 0 };\n    public meridian = true;\n}\n";
const meridianHtml = "<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\" meridian=\"example.meridian\"></ngb-timepicker>\n    <button type=\"button\" class=\"btn btn-sm\" ng-class=\"example.meridian ? 'btn-outline-success' : 'btn-outline-secondary'\" ng-click=\"example.meridian = !example.meridian\">\n        Meridian {{ example.meridian ? 'on' : 'off' }}\n    </button>\n    <hr class=\"w-100 my-0\">\n    <pre class=\"w-100 mb-0\">Selected time: {{ example.time | json }}</pre>\n</div>\n";
const secondsTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-seconds-timepicker\",\n    controllerAs: \"example\",\n    templateUrl: \"./seconds-timepicker.component.html\",\n    styleUrl: \"./seconds-timepicker.component.css\",\n})\nexport class SecondsTimepickerComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 25 };\n    public seconds = true;\n}\n";
const secondsHtml = "<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\" seconds=\"example.seconds\"></ngb-timepicker>\n    <button type=\"button\" class=\"btn btn-sm\" ng-class=\"example.seconds ? 'btn-outline-success' : 'btn-outline-secondary'\" ng-click=\"example.seconds = !example.seconds\">\n        Seconds {{ example.seconds ? 'on' : 'off' }}\n    </button>\n    <hr class=\"w-100 my-0\">\n    <pre class=\"w-100 mb-0\">Selected time: {{ example.time | json }}</pre>\n</div>\n";
const spinnersTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-spinners-timepicker\",\n    controllerAs: \"example\",\n    templateUrl: \"./spinners-timepicker.component.html\",\n    styleUrl: \"./spinners-timepicker.component.css\",\n})\nexport class SpinnersTimepickerComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 0 };\n    public spinners = true;\n}\n";
const spinnersHtml = "<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\" spinners=\"example.spinners\"></ngb-timepicker>\n    <button type=\"button\" class=\"btn btn-sm\" ng-class=\"example.spinners ? 'btn-outline-success' : 'btn-outline-secondary'\" ng-click=\"example.spinners = !example.spinners\">\n        Spinners {{ example.spinners ? 'on' : 'off' }}\n    </button>\n</div>\n";
const stepsTs = "import { Component } from \"ngjs-core\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-timepicker-custom-steps\",\n    controllerAs: \"example\",\n    templateUrl: \"./timepicker-custom-steps.component.html\",\n    styleUrl: \"./timepicker-custom-steps.component.css\",\n})\nexport class TimepickerCustomStepsComponent {\n    public time: NgbTimeStruct = { hour: 13, minute: 30, second: 0 };\n    public hourStep = 1;\n    public minuteStep = 15;\n    public secondStep = 30;\n}\n";
const stepsHtml = "<div class=\"d-flex flex-column align-items-start gap-3\">\n    <ngb-timepicker ng-model=\"example.time\" seconds=\"true\" hour-step=\"example.hourStep\" minute-step=\"example.minuteStep\" second-step=\"example.secondStep\"></ngb-timepicker>\n\n    <div class=\"row g-3 align-self-stretch\">\n        <div class=\"col-sm-4\">\n            <label class=\"form-label small\" for=\"timepicker-hour-step\">Hour step</label>\n            <input id=\"timepicker-hour-step\" class=\"form-control form-control-sm\" type=\"number\" min=\"1\" ng-model=\"example.hourStep\">\n        </div>\n        <div class=\"col-sm-4\">\n            <label class=\"form-label small\" for=\"timepicker-minute-step\">Minute step</label>\n            <input id=\"timepicker-minute-step\" class=\"form-control form-control-sm\" type=\"number\" min=\"1\" ng-model=\"example.minuteStep\">\n        </div>\n        <div class=\"col-sm-4\">\n            <label class=\"form-label small\" for=\"timepicker-second-step\">Second step</label>\n            <input id=\"timepicker-second-step\" class=\"form-control form-control-sm\" type=\"number\" min=\"1\" ng-model=\"example.secondStep\">\n        </div>\n    </div>\n\n    <hr class=\"w-100 my-0\">\n    <pre class=\"w-100 mb-0\">Selected time: {{ example.time | json }}</pre>\n</div>\n";
const validationTs = "import { Component, Directive, forwardRef } from \"ngjs-core\";\nimport { type AbstractControl, NG_VALIDATORS, type ValidationErrors, type Validator } from \"ngjs-core/forms\";\nimport type { NgbTimeStruct } from \"ngb-js/timepicker\";\n\n@Component({\n    selector: \"docs-timepicker-validation\",\n    controllerAs: \"example\",\n    templateUrl: \"./timepicker-validation.component.html\",\n    styleUrl: \"./timepicker-validation.component.css\",\n})\nexport class TimepickerValidationComponent {\n    public time: NgbTimeStruct | null = null;\n}\n\n@Directive({\n    selector: \"[docsTimepickerLunchValidator]\",\n    providers: [{ provide: NG_VALIDATORS, useExisting: forwardRef(() => TimepickerLunchValidatorDirective), multi: true }],\n})\nexport class TimepickerLunchValidatorDirective implements Validator {\n    public validate(control: AbstractControl): ValidationErrors | null {\n        const time = control.value as NgbTimeStruct | null;\n        return !time || (time.hour >= 12 && time.hour <= 13) ? null : { lunchtime: true };\n    }\n}\n";
const validationHtml = "<p>Select a time between 12:00 and 13:59.</p>\n\n<form name=\"example.form\" novalidate>\n    <div class=\"d-flex flex-column align-items-start gap-2\">\n        <ngb-timepicker name=\"lunchtime\" ng-model=\"example.time\" docs-timepicker-lunch-validator required></ngb-timepicker>\n\n        <div class=\"small text-success\" ng-if=\"example.form.lunchtime.$valid\">Great choice.</div>\n        <div class=\"small text-danger\" ng-if=\"example.form.lunchtime.$error.required\">Select a lunchtime.</div>\n        <div class=\"small text-danger\" ng-if=\"example.form.lunchtime.$error.lunchtime\">The selected time is too early or too late.</div>\n    </div>\n</form>\n\n<hr>\n<pre class=\"w-100 mb-0\">Selected time: {{ example.time | json }}</pre>\n";

@Component({
    selector: "docs-timepicker-examples-page",
    controllerAs: "$",
    templateUrl: "./timepicker-examples-page.component.html",
    styleUrl: "./timepicker-examples-page.component.css",
})
export class TimepickerExamplesPageComponent {
    public readonly examples = {
        basic: { html: basicHtml, typescript: basicTs },
        meridian: { html: meridianHtml, typescript: meridianTs },
        seconds: { html: secondsHtml, typescript: secondsTs },
        spinners: { html: spinnersHtml, typescript: spinnersTs },
        steps: { html: stepsHtml, typescript: stepsTs },
        validation: { html: validationHtml, typescript: validationTs },
        adapter: { html: adapterHtml, typescript: adapterTs },
        i18n: { html: i18nHtml, typescript: i18nTs },
    }
}
