import { Component } from "ngjs-core";
const closeableHtml = "<div class=\"toast-container position-static\">\n    <ngb-toast ng-if=\"example.visible\" header=\"Close me\" autohide=\"false\" hidden=\"example.close()\">\n        Use the close button in the header. This toast will return after three seconds.\n    </ngb-toast>\n\n    <div ng-if=\"!example.visible\" class=\"alert alert-light border mb-0\" role=\"status\">\n        The toast will be back shortly.\n    </div>\n</div>\n";
const closeableTs = "import { Component, type OnDestroy } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-closeable-toast\",\n    controllerAs: \"example\",\n    templateUrl: \"./closeable-toast.component.html\",\n    styleUrl: \"./closeable-toast.component.css\",\n})\nexport class CloseableToastComponent implements OnDestroy {\n    public visible = true;\n    private reopenTimer?: ReturnType<typeof setTimeout>;\n\n    public close(): void {\n        this.visible = false;\n        this.reopenTimer = setTimeout(() => {\n            this.visible = true;\n        }, 3000);\n    }\n\n    public ngOnDestroy(): void {\n        if (this.reopenTimer) clearTimeout(this.reopenTimer);\n    }\n}\n";
const inlineHtml = "<div class=\"toast-container position-static d-flex flex-column gap-3\">\n    <div>\n        <h3 class=\"h6\">Body only</h3>\n        <ngb-toast autohide=\"false\">I am a simple static toast.</ngb-toast>\n    </div>\n\n    <div>\n        <h3 class=\"h6\">With a text header</h3>\n        <ngb-toast ng-if=\"example.showHeaderToast\" header=\"Hello\" autohide=\"false\" hidden=\"example.showHeaderToast = false\">\n            I am a simple static toast with a header.\n        </ngb-toast>\n        <button ng-if=\"!example.showHeaderToast\" type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.showHeaderToast = true\">\n            Show toast again\n        </button>\n    </div>\n</div>\n";
const inlineTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-inline-toast\",\n    controllerAs: \"example\",\n    templateUrl: \"./inline-toast.component.html\",\n    styleUrl: \"./inline-toast.component.css\",\n})\nexport class InlineToastComponent {\n    public showHeaderToast = true;\n}\n";
const managementHtml = "<div class=\"d-flex flex-wrap gap-2 mb-3\">\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.showStandard()\">Standard</button>\n    <button type=\"button\" class=\"btn btn-success\" ng-click=\"example.showSuccess()\">Success</button>\n    <button type=\"button\" class=\"btn btn-danger\" ng-click=\"example.showDanger()\">Danger</button>\n    <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"example.toastService.clear()\" disabled=\"!example.toastService.toasts.length\">Clear all</button>\n</div>\n\n<div class=\"toast-container position-static d-flex flex-column gap-2\" aria-live=\"polite\" aria-atomic=\"true\">\n    <ngb-toast\n        ng-repeat=\"toast in example.toastService.toasts track by toast.id\"\n        class=\"{{ toast.className }}\"\n        autohide=\"true\"\n        delay=\"toast.delay || 5000\"\n        hidden=\"example.toastService.remove(toast)\">\n        {{ toast.body }}\n    </ngb-toast>\n\n    <p ng-if=\"!example.toastService.toasts.length\" class=\"small text-body-secondary mb-0\">No active toasts.</p>\n</div>\n";
const managementTs = "import { Component, Injectable, type OnDestroy } from \"ngjs-core\";\n\ninterface ManagedToast {\n    id: number;\n    body: string;\n    className?: string;\n    delay?: number;\n}\n\n@Injectable()\nexport class DocsToastService {\n    public readonly toasts: ManagedToast[] = [];\n    private nextId = 0;\n\n    public show(body: string, options: Omit<ManagedToast, \"id\" | \"body\"> = {}): void {\n        this.toasts.push({ id: ++this.nextId, body, ...options });\n    }\n\n    public remove(toast: ManagedToast): void {\n        const index = this.toasts.indexOf(toast);\n        if (index >= 0) this.toasts.splice(index, 1);\n    }\n\n    public clear(): void {\n        this.toasts.length = 0;\n    }\n}\n\n@Component({\n    selector: \"docs-toast-management\",\n    controllerAs: \"example\",\n    templateUrl: \"./toast-management.component.html\",\n    styleUrl: \"./toast-management.component.css\",\n})\nexport class ToastManagementComponent implements OnDestroy {\n    constructor(public readonly toastService: DocsToastService) {}\n\n    public showStandard(): void {\n        this.toastService.show(\"I am a standard toast.\");\n    }\n\n    public showSuccess(): void {\n        this.toastService.show(\"Your changes were saved.\", { className: \"bg-success text-white\", delay: 8000 });\n    }\n\n    public showDanger(): void {\n        this.toastService.show(\"The operation could not be completed.\", { className: \"bg-danger text-white\", delay: 10000 });\n    }\n\n    public ngOnDestroy(): void {\n        this.toastService.clear();\n    }\n}\n";
const preventAutohideHtml = "<p>Show the toast and keep the pointer over it to pause autohide.</p>\n\n<button type=\"button\" class=\"btn btn-primary mb-3\" ng-click=\"example.show()\">Show toast</button>\n\n<div class=\"toast-container position-static\">\n    <ngb-toast\n        ng-if=\"example.visible\"\n        header=\"Autohide can be paused\"\n        delay=\"5000\"\n        autohide=\"example.autohide\"\n        hidden=\"example.hide()\"\n        ng-mouseenter=\"example.autohide = false\"\n        ng-mouseleave=\"example.autohide = true\"\n        ng-class=\"{ 'border-warning': !example.autohide }\">\n        {{ example.autohide ? 'Hover over me before five seconds pass.' : 'Paused. I will remain visible until you leave.' }}\n    </ngb-toast>\n</div>\n";
const preventAutohideTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-prevent-autohide-toast\",\n    controllerAs: \"example\",\n    templateUrl: \"./prevent-autohide-toast.component.html\",\n    styleUrl: \"./prevent-autohide-toast.component.css\",\n})\nexport class PreventAutohideToastComponent {\n    public visible = false;\n    public autohide = true;\n\n    public show(): void {\n        this.visible = false;\n        this.autohide = true;\n        setTimeout(() => this.visible = true);\n    }\n\n    public hide(): void {\n        this.visible = false;\n        this.autohide = true;\n    }\n}\n";
const templateHeaderHtml = "<div class=\"toast-container position-static\">\n    <ngb-toast ng-if=\"example.visible\" autohide=\"false\" hidden=\"example.visible = false\">\n        <ng-template ngb-toast-header>\n            <div class=\"d-flex align-items-center gap-2 me-auto\">\n                <i class=\"bi bi-stars text-primary\" aria-hidden=\"true\"></i>\n                <strong>Custom header</strong>\n                <small class=\"text-body-secondary\">just now</small>\n            </div>\n        </ng-template>\n        The complete header is rendered from an <code>ng-template</code>.\n    </ngb-toast>\n\n    <button ng-if=\"!example.visible\" type=\"button\" class=\"btn btn-sm btn-outline-primary\" ng-click=\"example.visible = true\">\n        Show toast again\n    </button>\n</div>\n";
const templateHeaderTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-template-header-toast\",\n    controllerAs: \"example\",\n    templateUrl: \"./template-header-toast.component.html\",\n    styleUrl: \"./template-header-toast.component.css\",\n})\nexport class TemplateHeaderToastComponent {\n    public visible = true;\n}\n";

@Component({
    selector: "docs-toast-examples-page",
    controllerAs: "$",
    templateUrl: "./toast-examples-page.component.html",
    styleUrl: "./toast-examples-page.component.css",
})
export class ToastExamplesPageComponent {
    public readonly examples = {
        inline: { html: inlineHtml, typescript: inlineTs },
        templateHeader: { html: templateHeaderHtml, typescript: templateHeaderTs },
        closeable: { html: closeableHtml, typescript: closeableTs },
        preventAutohide: { html: preventAutohideHtml, typescript: preventAutohideTs },
        management: { html: managementHtml, typescript: managementTs },
    }
}
