import { Component } from "ngjs-core";
const alternativeNavHtml = "<nav\n    ngb-nav\n    ng-ref=\"example.nav\"\n    ng-ref-read=\"ngbNav\"\n    active-id=\"example.activeId\"\n    class=\"nav-tabs\">\n    <div ngb-nav-item=\"'alternative-home'\">\n        <button type=\"button\" ngb-nav-link>Button link</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">This item uses a button without list markup.</p>\n        </ng-template>\n    </div>\n    <div ngb-nav-item=\"'alternative-profile'\">\n        <a ngb-nav-link>Anchor link</a>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">This item uses an anchor inside a plain div.</p>\n        </ng-template>\n    </div>\n    <div ngb-nav-item=\"'alternative-contact'\">\n        <button type=\"button\" ngb-nav-link>Another button</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">Buttons and anchors can be interchanged.</p>\n        </ng-template>\n    </div>\n</nav>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n";
const alternativeNavTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-alternative-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./alternative-nav.component.html\",\n    styleUrl: \"./alternative-nav.component.css\",\n})\nexport class AlternativeNavComponent {\n    public activeId = \"alternative-home\";\n}\n";
const customNavCss = ".nav-demo { gap: .35rem; padding: .4rem; border: 1px solid var(--bs-border-color); border-radius: 999px; background: color-mix(in srgb, var(--bs-tertiary-bg) 82%, var(--bs-body-bg)); box-shadow: inset 0 1px 0 rgba(255, 255, 255, .05); }\n.nav-demo .nav-link { border-radius: 999px; color: var(--bs-secondary-color); }\n.nav-demo .nav-link:hover { color: var(--bs-emphasis-color); background: var(--bs-body-bg); }\n.nav-demo .nav-link.active { color: var(--bs-primary-text-emphasis); background: var(--bs-primary-bg-subtle); box-shadow: 0 .35rem 1rem rgba(var(--bs-body-color-rgb), .08); }\n";
const customNavHtml = "<div\n    ngb-nav\n    ng-ref=\"example.nav\"\n    ng-ref-read=\"ngbNav\"\n    active-id=\"example.activeId\"\n    roles=\"false\"\n    class=\"nav-demo\">\n    <div ngb-nav-item=\"'custom-daily'\">\n        <button type=\"button\" ngb-nav-link>Daily</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">Daily activity summary.</p></ng-template>\n    </div>\n    <div ngb-nav-item=\"'custom-weekly'\">\n        <button type=\"button\" ngb-nav-link>Weekly</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">Weekly activity summary.</p></ng-template>\n    </div>\n    <div ngb-nav-item=\"'custom-monthly'\">\n        <button type=\"button\" ngb-nav-link>Monthly</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">Monthly activity summary.</p></ng-template>\n    </div>\n</div>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n";
const customNavTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-custom-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./custom-nav.component.html\",\n    styleUrl: \"./custom-nav.component.css\",\n})\nexport class CustomNavComponent {\n    public activeId = \"custom-weekly\";\n}\n";
const dynamicNavHtml = "<div class=\"d-flex flex-wrap gap-2 mb-3\">\n    <button type=\"button\" class=\"btn btn-primary btn-sm\" ng-click=\"example.add()\">Add tab</button>\n    <button\n        type=\"button\"\n        class=\"btn btn-outline-danger btn-sm\"\n        ng-click=\"example.removeActive()\"\n        disabled=\"example.items.length === 1\">\n        Remove active tab\n    </button>\n</div>\n\n<ul\n    ngb-nav\n    ng-ref=\"example.nav\"\n    ng-ref-read=\"ngbNav\"\n    active-id=\"example.activeId\"\n    class=\"nav-tabs\">\n    <li ng-repeat=\"item in example.items track by item.id\" ngb-nav-item=\"item.id\">\n        <button type=\"button\" ngb-nav-link>{{ item.title }}</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">Dynamic content for {{ item.title }}.</p>\n        </ng-template>\n    </li>\n</ul>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n";
const dynamicNavTs = "import { Component } from \"ngjs-core\";\n\ninterface DynamicNavItem {\n    id: string;\n    title: string;\n}\n\n@Component({\n    selector: \"docs-dynamic-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./dynamic-nav.component.html\",\n    styleUrl: \"./dynamic-nav.component.css\",\n})\nexport class DynamicNavComponent {\n    public items: DynamicNavItem[] = [\n        { id: \"dynamic-1\", title: \"Tab 1\" },\n        { id: \"dynamic-2\", title: \"Tab 2\" },\n        { id: \"dynamic-3\", title: \"Tab 3\" },\n    ];\n    public activeId = \"dynamic-1\";\n    private nextId = 4;\n\n    public add() {\n        const item = {\n            id: `dynamic-${this.nextId}`,\n            title: `Tab ${this.nextId}`,\n        };\n\n        this.nextId++;\n        this.items.push(item);\n        this.activeId = item.id;\n    }\n\n    public removeActive() {\n        if (this.items.length === 1) return;\n\n        const activeIndex = this.items.findIndex(({ id }) => id === this.activeId);\n        const replacement = this.items[activeIndex === 0 ? 1 : activeIndex - 1];\n\n        this.activeId = replacement.id;\n        this.items = this.items.filter(({ id }) => id !== this.items[activeIndex].id);\n    }\n}\n";
const keepContentNavHtml = "<ul\n    ngb-nav\n    ng-ref=\"example.nav\"\n    ng-ref-read=\"ngbNav\"\n    active-id=\"example.activeId\"\n    destroy-on-hide=\"false\"\n    class=\"nav-tabs\">\n    <li ngb-nav-item=\"'keep-editor'\">\n        <button type=\"button\" ngb-nav-link>Editor</button>\n        <ng-template ngb-nav-content>\n            <div class=\"pt-3\">\n                <label class=\"form-label\" for=\"keep-content-draft\">Draft</label>\n                <input id=\"keep-content-draft\" type=\"text\" class=\"form-control\" ng-model=\"example.draft\">\n            </div>\n        </ng-template>\n    </li>\n    <li ngb-nav-item=\"'keep-preview'\">\n        <button type=\"button\" ngb-nav-link>Preview</button>\n        <ng-template ngb-nav-content>\n            <div class=\"pt-3\">\n                <p class=\"small text-body-secondary mb-1\">Current draft</p>\n                <p class=\"mb-0\">{{ example.draft }}</p>\n            </div>\n        </ng-template>\n    </li>\n</ul>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n";
const keepContentNavTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-keep-content-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./keep-content-nav.component.html\",\n    styleUrl: \"./keep-content-nav.component.css\",\n})\nexport class KeepContentNavComponent {\n    public activeId = \"keep-editor\";\n    public draft = \"This value survives tab changes.\";\n}\n";
const navGlobalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">\n            The nav is vertical, keeps hidden content and selects tabs while navigating with the arrow keys.\n        </p>\n    </div>\n</div>\n\n<div class=\"d-flex align-items-start gap-3\">\n    <div\n        ngb-nav\n        ng-ref=\"example.nav\"\n        ng-ref-read=\"ngbNav\"\n        active-id=\"example.activeId\"\n        class=\"nav-pills flex-column flex-shrink-0\">\n        <div ngb-nav-item=\"'global-account'\">\n            <button type=\"button\" ngb-nav-link>Account</button>\n            <ng-template ngb-nav-content><p class=\"mb-0\">Global account settings.</p></ng-template>\n        </div>\n        <div ngb-nav-item=\"'global-team'\">\n            <button type=\"button\" ngb-nav-link>Team</button>\n            <ng-template ngb-nav-content><p class=\"mb-0\">Global team settings.</p></ng-template>\n        </div>\n        <div ngb-nav-item=\"'global-billing'\">\n            <button type=\"button\" ngb-nav-link>Billing</button>\n            <ng-template ngb-nav-content><p class=\"mb-0\">Global billing settings.</p></ng-template>\n        </div>\n    </div>\n\n    <div class=\"border rounded p-3 flex-grow-1\" ngb-nav-outlet=\"example.nav\"></div>\n</div>\n";
const navGlobalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbNavConfig } from \"ngb-js/nav\";\n\n@Component({\n    selector: \"docs-nav-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./nav-global.component.html\",\n    styleUrl: \"./nav-global.component.css\",\n})\nexport class NavGlobalComponent implements AfterViewInit, OnDestroy {\n    public activeId = \"global-account\";\n\n    private readonly initialConfig: Pick<\n        NgbNavConfig,\n        \"animation\" | \"destroyOnHide\" | \"keyboard\" | \"orientation\" | \"roles\"\n    >;\n\n    constructor(private readonly config: NgbNavConfig) {\n        this.initialConfig = {\n            animation: config.animation,\n            destroyOnHide: config.destroyOnHide,\n            keyboard: config.keyboard,\n            orientation: config.orientation,\n            roles: config.roles,\n        };\n\n        config.animation = false;\n        config.destroyOnHide = false;\n        config.keyboard = \"changeWithArrows\";\n        config.orientation = \"vertical\";\n        config.roles = \"tablist\";\n    }\n\n    public ngAfterViewInit() {\n        this.restoreConfig();\n    }\n\n    public ngOnDestroy() {\n        this.restoreConfig();\n    }\n\n    private restoreConfig() {\n        this.config.animation = this.initialConfig.animation;\n        this.config.destroyOnHide = this.initialConfig.destroyOnHide;\n        this.config.keyboard = this.initialConfig.keyboard;\n        this.config.orientation = this.initialConfig.orientation;\n        this.config.roles = this.initialConfig.roles;\n    }\n}\n";
const selectingNavHtml = "<div class=\"d-flex flex-wrap gap-2 mb-3\">\n    <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"example.select('selecting-first')\">\n        Select first\n    </button>\n    <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"example.select('selecting-second')\">\n        Select second\n    </button>\n    <button type=\"button\" class=\"btn btn-outline-primary btn-sm\" ng-click=\"example.select('selecting-third')\">\n        Select third\n    </button>\n</div>\n\n<ul ngb-nav ng-ref=\"example.nav\" ng-ref-read=\"ngbNav\" active-id=\"example.activeId\" class=\"nav-tabs\">\n    <li ngb-nav-item=\"'selecting-first'\">\n        <button type=\"button\" ngb-nav-link>First</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">First tab selected.</p></ng-template>\n    </li>\n    <li ngb-nav-item=\"'selecting-second'\">\n        <button type=\"button\" ngb-nav-link>Second</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">Second tab selected.</p></ng-template>\n    </li>\n    <li ngb-nav-item=\"'selecting-third'\">\n        <button type=\"button\" ngb-nav-link>Third</button>\n        <ng-template ngb-nav-content><p class=\"pt-3 mb-0\">Third tab selected.</p></ng-template>\n    </li>\n</ul>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n<p class=\"small text-body-secondary mt-2 mb-0\">Active id: {{ example.activeId }}</p>\n";
const selectingNavTs = "import { Component } from \"ngjs-core\";\nimport { NgbNav } from \"ngb-js/nav\";\n\n@Component({\n    selector: \"docs-selecting-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./selecting-nav.component.html\",\n    styleUrl: \"./selecting-nav.component.css\",\n})\nexport class SelectingNavComponent {\n    public nav!: NgbNav;\n\n    public activeId = \"selecting-first\";\n\n    public select(id: string) {\n        this.nav.select(id);\n    }\n}\n";
const simpleNavHtml = "<ul\n    ngb-nav\n    ng-ref=\"example.nav\"\n    ng-ref-read=\"ngbNav\"\n    active-id=\"example.activeId\"\n    class=\"nav-tabs\">\n    <li ngb-nav-item=\"'simple-overview'\">\n        <button type=\"button\" ngb-nav-link>Overview</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">A concise overview of the current project.</p>\n        </ng-template>\n    </li>\n    <li ngb-nav-item=\"'simple-features'\">\n        <button type=\"button\" ngb-nav-link>Features</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">Explore the features exposed by this library.</p>\n        </ng-template>\n    </li>\n    <li ngb-nav-item=\"'simple-settings'\">\n        <button type=\"button\" ngb-nav-link>Settings</button>\n        <ng-template ngb-nav-content>\n            <p class=\"pt-3 mb-0\">Adjust the settings for this example.</p>\n        </ng-template>\n    </li>\n</ul>\n\n<div ngb-nav-outlet=\"example.nav\"></div>\n";
const simpleNavTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-simple-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./simple-nav.component.html\",\n    styleUrl: \"./simple-nav.component.css\",\n})\nexport class SimpleNavComponent {\n    public activeId = \"simple-overview\";\n}\n";
const verticalNavHtml = "<div class=\"d-flex align-items-start gap-3\">\n    <div\n        ngb-nav\n        ng-ref=\"example.nav\"\n        ng-ref-read=\"ngbNav\"\n        active-id=\"example.activeId\"\n        orientation=\"'vertical'\"\n        class=\"nav-pills flex-shrink-0\">\n        <div ngb-nav-item=\"'vertical-profile'\">\n            <button type=\"button\" ngb-nav-link>Profile</button>\n            <ng-template ngb-nav-content>\n                <h3 class=\"h5\">Profile</h3>\n                <p class=\"mb-0\">Manage your public information and preferences.</p>\n            </ng-template>\n        </div>\n        <div ngb-nav-item=\"'vertical-security'\">\n            <button type=\"button\" ngb-nav-link>Security</button>\n            <ng-template ngb-nav-content>\n                <h3 class=\"h5\">Security</h3>\n                <p class=\"mb-0\">Review sessions, passwords and account access.</p>\n            </ng-template>\n        </div>\n        <div ngb-nav-item=\"'vertical-notifications'\">\n            <button type=\"button\" ngb-nav-link>Notifications</button>\n            <ng-template ngb-nav-content>\n                <h3 class=\"h5\">Notifications</h3>\n                <p class=\"mb-0\">Choose when and how the application contacts you.</p>\n            </ng-template>\n        </div>\n    </div>\n\n    <div class=\"border rounded p-3 flex-grow-1\" ngb-nav-outlet=\"example.nav\"></div>\n</div>\n";
const verticalNavTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-vertical-nav\",\n    controllerAs: \"example\",\n    templateUrl: \"./vertical-nav.component.html\",\n    styleUrl: \"./vertical-nav.component.css\",\n})\nexport class VerticalNavComponent {\n    public activeId = \"vertical-profile\";\n}\n";

@Component({
    selector: "docs-nav-examples-page",
    controllerAs: "$",
    templateUrl: "./nav-examples-page.component.html",
    styleUrl: "./nav-examples-page.component.css",
})
export class NavExamplesPageComponent {
    public readonly examples = {
        simple: {
            html: simpleNavHtml,
            typescript: simpleNavTs,
        },
        alternative: {
            html: alternativeNavHtml,
            typescript: alternativeNavTs,
        },
        vertical: {
            html: verticalNavHtml,
            typescript: verticalNavTs,
        },
        selecting: {
            html: selectingNavHtml,
            typescript: selectingNavTs,
        },
        keepContent: {
            html: keepContentNavHtml,
            typescript: keepContentNavTs,
        },
        dynamic: {
            html: dynamicNavHtml,
            typescript: dynamicNavTs,
        },
        custom: {
            html: customNavHtml,
            typescript: customNavTs,
            css: customNavCss,
        },
        global: {
            html: navGlobalHtml,
            typescript: navGlobalTs,
        },
    }
}
