import { Component } from "ngjs-core";
const offcanvasComponentContentHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open component offcanvas</button>\n<p class=\"small text-body-secondary mt-2 mb-0\">{{ example.lastResult }}</p>\n";
const offcanvasComponentContentTs = "import { Component } from \"ngjs-core\";\nimport { OffcanvasDemoContentComponent } from \"@/features/offcanvas/components/offcanvas-demo-content/offcanvas-demo-content.component\"\nimport { NgbOffcanvas } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-component-content\",\n    controllerAs: \"example\",\n    templateUrl: \"./offcanvas-component-content.component.html\",\n    styleUrl: \"./offcanvas-component-content.component.css\",\n})\nexport class OffcanvasComponentContentComponent {\n    public lastResult = \"No result yet\";\n\n    constructor(private readonly offcanvas: NgbOffcanvas) {}\n\n    public async open() {\n        const offcanvasRef = await this.offcanvas.open(OffcanvasDemoContentComponent);\n\n        offcanvasRef.closed.subscribe((result) => {\n            this.lastResult = `Closed with: ${result}`;\n        });\n\n        offcanvasRef.dismissed.subscribe((reason) => {\n            this.lastResult = `Dismissed with: ${reason}`;\n        });\n    }\n}\n";
const offcanvasDefaultHtml = "<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open default offcanvas</button>\n\n<ng-template ng-ref=\"content\" let-close=\"close\" let-dismiss=\"dismiss\">\n    <div class=\"offcanvas-header\">\n        <h2 class=\"offcanvas-title fs-5\">Default offcanvas</h2>\n        <button type=\"button\" class=\"btn-close\" aria-label=\"Close\" ng-click=\"dismiss('header close')\"></button>\n    </div>\n    <div class=\"offcanvas-body\">\n        <p>This offcanvas uses the global defaults without passing local options.</p>\n        <div class=\"d-flex flex-wrap gap-2\">\n            <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"dismiss('cancel')\">Cancel</button>\n            <button type=\"button\" class=\"btn btn-primary\" ng-click=\"close('accepted')\">Continue</button>\n        </div>\n    </div>\n</ng-template>\n";
const offcanvasDefaultTs = "import { Component, TemplateRef, ViewChild } from \"ngjs-core\";\nimport { NgbOffcanvas } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-default\",\n    controllerAs: \"example\",\n    templateUrl: \"./offcanvas-default.component.html\",\n    styleUrl: \"./offcanvas-default.component.css\",\n})\nexport class OffcanvasDefaultComponent {\n    @ViewChild(\"content\", { read: TemplateRef, static: true })\n    private content!: TemplateRef<unknown>;\n\n    constructor(private readonly offcanvas: NgbOffcanvas) {}\n\n    public open() {\n        this.offcanvas.open(this.content);\n    }\n}\n";
const offcanvasDemoContentHtml = "<div class=\"offcanvas-header\">\n    <h2 class=\"offcanvas-title fs-5\">Component offcanvas</h2>\n    <button\n        type=\"button\"\n        class=\"btn-close\"\n        aria-label=\"Close\"\n        ng-click=\"$.ngbActiveOffcanvas.dismiss('header close')\">\n    </button>\n</div>\n\n<div class=\"offcanvas-body\">\n    <p>This panel receives a registered component as its content.</p>\n    <div class=\"d-flex flex-wrap gap-2\">\n        <button type=\"button\" class=\"btn btn-outline-secondary\" ng-click=\"$.ngbActiveOffcanvas.dismiss('cancel')\">\n            Cancel\n        </button>\n        <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveOffcanvas.close('accepted')\">\n            Continue\n        </button>\n    </div>\n</div>\n";
const offcanvasDemoContentTs = "import { Component, Input } from \"ngjs-core\";\nimport type { NgbActiveOffcanvas } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-demo-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./offcanvas-demo-content.component.html\",\n    styleUrl: \"./offcanvas-demo-content.component.css\",\n})\nexport class OffcanvasDemoContentComponent {\n    @Input() ngbActiveOffcanvas!: NgbActiveOffcanvas;\n}\n";
const offcanvasFocusHtml = "<p class=\"text-body-secondary\">\n    The first focusable element receives focus by default. Add <code>ngbAutofocus</code> to choose another target.\n</p>\n\n<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.openDefaultFocus()\">Focus first element</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCustomFocus()\">Use ngbAutofocus</button>\n</div>\n";
const offcanvasFocusTs = "import { Component } from \"ngjs-core\";\nimport { OffcanvasFocusContentComponent } from \"@/features/offcanvas/components/offcanvas-focus-content/offcanvas-focus-content.component\"\nimport { NgbOffcanvas } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-focus\",\n    controllerAs: \"example\",\n    templateUrl: \"./offcanvas-focus.component.html\",\n    styleUrl: \"./offcanvas-focus.component.css\",\n})\nexport class OffcanvasFocusComponent {\n    constructor(private readonly offcanvas: NgbOffcanvas) {}\n\n    public openDefaultFocus() {\n        this.offcanvas.open(OffcanvasFocusContentComponent, {\n            ariaLabelledBy: \"offcanvas-focus-title\",\n            bindings: { autofocus: false },\n        });\n    }\n\n    public openCustomFocus() {\n        this.offcanvas.open(OffcanvasFocusContentComponent, {\n            ariaLabelledBy: \"offcanvas-focus-title\",\n            bindings: { autofocus: true },\n        });\n    }\n}\n";
const offcanvasFocusContentHtml = "<div class=\"offcanvas-header\">\n    <h2 class=\"offcanvas-title fs-5\" id=\"offcanvas-focus-title\">Focus management</h2>\n</div>\n\n<div class=\"offcanvas-body\">\n    <div class=\"mb-3\">\n        <label class=\"form-label\" for=\"offcanvas-first-focusable\">First focusable element</label>\n        <input id=\"offcanvas-first-focusable\" type=\"text\" class=\"form-control\" placeholder=\"Focused by default\">\n    </div>\n\n    <div class=\"mb-3\" ng-if=\"$.autofocus\">\n        <label class=\"form-label\" for=\"offcanvas-custom-autofocus\">Custom autofocus target</label>\n        <input\n            id=\"offcanvas-custom-autofocus\"\n            type=\"text\"\n            class=\"form-control\"\n            placeholder=\"Focused through ngbAutofocus\"\n            ngbAutofocus>\n    </div>\n\n    <button type=\"button\" class=\"btn btn-primary\" ng-click=\"$.ngbActiveOffcanvas.close()\">Done</button>\n</div>\n";
const offcanvasFocusContentTs = "import { Component, Input } from \"ngjs-core\";\nimport type { NgbActiveOffcanvas } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-focus-content\",\n    controllerAs: \"$\",\n    templateUrl: \"./offcanvas-focus-content.component.html\",\n    styleUrl: \"./offcanvas-focus-content.component.css\",\n})\nexport class OffcanvasFocusContentComponent {\n    @Input() ngbActiveOffcanvas!: NgbActiveOffcanvas;\n    @Input() autofocus = false;\n}\n";
const offcanvasGlobalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">\n            The panel opens from the end, allows body scrolling, uses a static backdrop and ignores Escape.\n            This documentation example restores the shared defaults immediately after opening.\n        </p>\n    </div>\n</div>\n\n<button type=\"button\" class=\"btn btn-primary\" ng-click=\"example.open()\">Open globally configured offcanvas</button>\n";
const offcanvasGlobalTs = "import { Component, type OnDestroy } from \"ngjs-core\";\nimport { OffcanvasDemoContentComponent } from \"@/features/offcanvas/components/offcanvas-demo-content/offcanvas-demo-content.component\"\nimport { NgbOffcanvas, NgbOffcanvasConfig } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./offcanvas-global.component.html\",\n    styleUrl: \"./offcanvas-global.component.css\",\n})\nexport class OffcanvasGlobalComponent implements OnDestroy {\n    private readonly initialConfig: Pick<\n        NgbOffcanvasConfig,\n        \"backdrop\" | \"keyboard\" | \"position\" | \"scroll\"\n    >;\n\n    constructor(\n        private readonly offcanvas: NgbOffcanvas,\n        private readonly config: NgbOffcanvasConfig,\n    ) {\n        this.initialConfig = {\n            backdrop: config.backdrop,\n            keyboard: config.keyboard,\n            position: config.position,\n            scroll: config.scroll,\n        };\n    }\n\n    public async open() {\n        this.applyConfig();\n\n        try {\n            await this.offcanvas.open(OffcanvasDemoContentComponent);\n        } finally {\n            this.restoreConfig();\n        }\n    }\n\n    public ngOnDestroy() {\n        this.restoreConfig();\n    }\n\n    private applyConfig() {\n        this.config.backdrop = \"static\";\n        this.config.keyboard = false;\n        this.config.position = \"end\";\n        this.config.scroll = true;\n    }\n\n    private restoreConfig() {\n        this.config.backdrop = this.initialConfig.backdrop;\n        this.config.keyboard = this.initialConfig.keyboard;\n        this.config.position = this.initialConfig.position;\n        this.config.scroll = this.initialConfig.scroll;\n    }\n}\n";
const offcanvasOptionsCss = ".panel { --bs-offcanvas-width: 28rem; border-color: var(--bs-primary-border-subtle); box-shadow: 0 1rem 3rem rgba(var(--bs-primary-rgb), .14); }\n.panel .offcanvas-header { background: color-mix(in srgb, var(--bs-primary-bg-subtle) 55%, var(--bs-body-bg)); }\n.backdrop { --bs-backdrop-bg: var(--bs-danger); --bs-backdrop-opacity: .35; }\n";
const offcanvasOptionsHtml = "<div class=\"d-flex flex-wrap gap-2\">\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openCustomPanel()\">Custom panel class</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openStaticBackdrop()\">Static backdrop</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openStart()\">Start</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openEnd()\">End</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openTop()\">Top</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openBottom()\">Bottom</button>\n    <button type=\"button\" class=\"btn btn-outline-primary\" ng-click=\"example.openScrollableBody()\">Body scrolling</button>\n</div>\n";
const offcanvasOptionsTs = "import { Component } from \"ngjs-core\";\nimport { OffcanvasDemoContentComponent } from \"@/features/offcanvas/components/offcanvas-demo-content/offcanvas-demo-content.component\"\nimport { NgbOffcanvas, type NgbOffcanvasOptions } from \"ngb-js/offcanvas\";\n\n@Component({\n    selector: \"docs-offcanvas-options\",\n    controllerAs: \"example\",\n    templateUrl: \"./offcanvas-options.component.html\",\n    styleUrl: \"./offcanvas-options.component.css\",\n})\nexport class OffcanvasOptionsComponent {\n    constructor(private readonly offcanvas: NgbOffcanvas) {}\n\n    public openCustomPanel() {\n        this.open({ panelClass: \"panel\" });\n    }\n\n    public openStaticBackdrop() {\n        this.open({\n            backdrop: \"static\",\n            backdropClass: \"backdrop\",\n            keyboard: false,\n        });\n    }\n\n    public openStart() {\n        this.open({ position: \"start\" });\n    }\n\n    public openEnd() {\n        this.open({ position: \"end\" });\n    }\n\n    public openTop() {\n        this.open({ position: \"top\" });\n    }\n\n    public openBottom() {\n        this.open({ position: \"bottom\" });\n    }\n\n    public openScrollableBody() {\n        this.open({ scroll: true, backdrop: false });\n    }\n\n    private open(options: NgbOffcanvasOptions) {\n        this.offcanvas.open(OffcanvasDemoContentComponent, options);\n    }\n}\n";

@Component({
    selector: "docs-offcanvas-examples-page",
    controllerAs: "$",
    templateUrl: "./offcanvas-examples-page.component.html",
    styleUrl: "./offcanvas-examples-page.component.css",
})
export class OffcanvasExamplesPageComponent {
    public readonly examples = {
        defaults: {
            html: offcanvasDefaultHtml,
            typescript: offcanvasDefaultTs,
        },
        componentContent: {
            html: `<!-- offcanvas-component-content.component.html -->\n${offcanvasComponentContentHtml}\n\n<!-- offcanvas-demo-content.component.html -->\n${offcanvasDemoContentHtml}`,
            typescript: `${offcanvasComponentContentTs}\n\n// offcanvas-demo-content.component.ts\n${offcanvasDemoContentTs}`,
        },
        focus: {
            html: `<!-- offcanvas-focus.component.html -->\n${offcanvasFocusHtml}\n\n<!-- offcanvas-focus-content.component.html -->\n${offcanvasFocusContentHtml}`,
            typescript: `${offcanvasFocusTs}\n\n// offcanvas-focus-content.component.ts\n${offcanvasFocusContentTs}`,
        },
        options: {
            html: offcanvasOptionsHtml,
            typescript: offcanvasOptionsTs,
            css: offcanvasOptionsCss,
        },
        global: {
            html: offcanvasGlobalHtml,
            typescript: offcanvasGlobalTs,
        },
    }
}
