import { Component } from "ngjs-core";
const advancedPaginationHtml = "<div class=\"vstack gap-4\">\n    <div>\n        <p class=\"small fw-semibold mb-2\">Restricted page range</p>\n        <ngb-pagination\n            collection-size=\"120\"\n            page=\"example.paginatedPage\"\n            page-change=\"example.selectPaginatedPage($event)\"\n            max-size=\"5\"\n            boundary-links=\"true\">\n        </ngb-pagination>\n    </div>\n\n    <div>\n        <p class=\"small fw-semibold mb-2\">Rotating page range</p>\n        <ngb-pagination\n            collection-size=\"240\"\n            page=\"example.rotatedPage\"\n            page-change=\"example.selectRotatedPage($event)\"\n            max-size=\"5\"\n            rotate=\"true\"\n            boundary-links=\"true\">\n        </ngb-pagination>\n    </div>\n\n    <div>\n        <p class=\"small fw-semibold mb-2\">Without ellipses</p>\n        <ngb-pagination\n            collection-size=\"240\"\n            page=\"example.compactPage\"\n            page-change=\"example.selectCompactPage($event)\"\n            max-size=\"5\"\n            rotate=\"true\"\n            ellipses=\"false\">\n        </ngb-pagination>\n    </div>\n</div>\n";
const advancedPaginationTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-advanced-pagination\",\n    controllerAs: \"example\",\n    templateUrl: \"./advanced-pagination.component.html\",\n    styleUrl: \"./advanced-pagination.component.css\",\n})\nexport class AdvancedPaginationComponent {\n    public paginatedPage = 7;\n    public rotatedPage = 12;\n    public compactPage = 12;\n\n    public selectPaginatedPage(page: number) { this.paginatedPage = page; }\n    public selectRotatedPage(page: number) { this.rotatedPage = page; }\n    public selectCompactPage(page: number) { this.compactPage = page; }\n}\n";
const basicPaginationHtml = "<ngb-pagination\n    collection-size=\"70\"\n    page=\"example.page\"\n    page-change=\"example.selectPage($event)\">\n</ngb-pagination>\n\n<p class=\"small text-body-secondary mb-0\">Current page: <strong>{{ example.page }}</strong></p>\n";
const basicPaginationTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-basic-pagination\",\n    controllerAs: \"example\",\n    templateUrl: \"./basic-pagination.component.html\",\n    styleUrl: \"./basic-pagination.component.css\",\n})\nexport class BasicPaginationComponent {\n    public page = 4;\n\n    public selectPage(page: number) {\n        this.page = page;\n    }\n}\n";
const customPaginationHtml = "<ngb-pagination\n    collection-size=\"50\"\n    page=\"example.page\"\n    page-change=\"example.selectPage($event)\">\n    <ng-template ngb-pagination-previous>\n        <span aria-hidden=\"true\">←</span> Previous\n    </ng-template>\n    <ng-template ngb-pagination-next>\n        Next <span aria-hidden=\"true\">→</span>\n    </ng-template>\n    <ng-template ngb-pagination-number let-page>\n        <span class=\"fw-semibold\">{{ page }}</span>\n    </ng-template>\n</ngb-pagination>\n";
const customPaginationTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-custom-pagination\",\n    controllerAs: \"example\",\n    templateUrl: \"./custom-pagination.component.html\",\n    styleUrl: \"./custom-pagination.component.css\",\n})\nexport class CustomPaginationComponent {\n    public page = 3;\n\n    public selectPage(page: number) {\n        this.page = page;\n    }\n}\n";
const disabledPaginationHtml = "<div class=\"form-check form-switch mb-3\">\n    <input class=\"form-check-input\" type=\"checkbox\" role=\"switch\" id=\"pagination-disabled\" ng-model=\"example.disabled\">\n    <label class=\"form-check-label\" for=\"pagination-disabled\">Disabled</label>\n</div>\n\n<ngb-pagination\n    collection-size=\"70\"\n    page=\"example.page\"\n    page-change=\"example.selectPage($event)\"\n    disabled=\"example.disabled\">\n</ngb-pagination>\n";
const disabledPaginationTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-disabled-pagination\",\n    controllerAs: \"example\",\n    templateUrl: \"./disabled-pagination.component.html\",\n    styleUrl: \"./disabled-pagination.component.css\",\n})\nexport class DisabledPaginationComponent {\n    public page = 3;\n    public disabled = true;\n\n    public selectPage(page: number) {\n        this.page = page;\n    }\n}\n";
const paginationAlignmentHtml = "<div class=\"vstack gap-4\">\n    <div>\n        <p class=\"small text-body-secondary mb-2\">Start</p>\n        <ngb-pagination class=\"d-flex justify-content-start\" collection-size=\"50\" page=\"example.startPage\" page-change=\"example.selectStartPage($event)\"></ngb-pagination>\n    </div>\n    <div>\n        <p class=\"small text-body-secondary text-center mb-2\">Center</p>\n        <ngb-pagination class=\"d-flex justify-content-center\" collection-size=\"50\" page=\"example.centerPage\" page-change=\"example.selectCenterPage($event)\"></ngb-pagination>\n    </div>\n    <div>\n        <p class=\"small text-body-secondary text-end mb-2\">End</p>\n        <ngb-pagination class=\"d-flex justify-content-end\" collection-size=\"50\" page=\"example.endPage\" page-change=\"example.selectEndPage($event)\"></ngb-pagination>\n    </div>\n</div>\n";
const paginationAlignmentTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-pagination-alignment\",\n    controllerAs: \"example\",\n    templateUrl: \"./pagination-alignment.component.html\",\n    styleUrl: \"./pagination-alignment.component.css\",\n})\nexport class PaginationAlignmentComponent {\n    public startPage = 2;\n    public centerPage = 2;\n    public endPage = 2;\n\n    public selectStartPage(page: number) { this.startPage = page; }\n    public selectCenterPage(page: number) { this.centerPage = page; }\n    public selectEndPage(page: number) { this.endPage = page; }\n}\n";
const paginationGlobalHtml = "<div class=\"alert alert-light border d-flex gap-3 align-items-start\" role=\"note\">\n    <i class=\"bi bi-gear text-primary mt-1\" aria-hidden=\"true\"></i>\n    <div>\n        <p class=\"fw-semibold mb-1\">Global defaults used by this example</p>\n        <p class=\"small text-body-secondary mb-0\">\n            Pagination is small, rotating, limited to five pages and uses boundary links without direction links.\n        </p>\n    </div>\n</div>\n\n<ngb-pagination\n    collection-size=\"200\"\n    page=\"example.page\"\n    page-change=\"example.selectPage($event)\">\n</ngb-pagination>\n";
const paginationGlobalTs = "import { Component, type AfterViewInit, type OnDestroy } from \"ngjs-core\";\nimport { NgbPaginationConfig } from \"ngb-js/pagination\";\n\n@Component({\n    selector: \"docs-pagination-global\",\n    controllerAs: \"example\",\n    templateUrl: \"./pagination-global.component.html\",\n    styleUrl: \"./pagination-global.component.css\",\n})\nexport class PaginationGlobalComponent implements AfterViewInit, OnDestroy {\n    public page = 8;\n\n    private readonly initialConfig: Pick<\n        NgbPaginationConfig,\n        \"boundaryLinks\" | \"directionLinks\" | \"maxSize\" | \"rotate\" | \"size\"\n    >;\n\n    constructor(private readonly config: NgbPaginationConfig) {\n        this.initialConfig = {\n            boundaryLinks: config.boundaryLinks,\n            directionLinks: config.directionLinks,\n            maxSize: config.maxSize,\n            rotate: config.rotate,\n            size: config.size,\n        };\n\n        config.boundaryLinks = true;\n        config.directionLinks = false;\n        config.maxSize = 5;\n        config.rotate = true;\n        config.size = \"sm\";\n    }\n\n    public selectPage(page: number) {\n        this.page = page;\n    }\n\n    public ngAfterViewInit() {\n        this.restoreConfig();\n    }\n\n    public ngOnDestroy() {\n        this.restoreConfig();\n    }\n\n    private restoreConfig() {\n        this.config.boundaryLinks = this.initialConfig.boundaryLinks;\n        this.config.directionLinks = this.initialConfig.directionLinks;\n        this.config.maxSize = this.initialConfig.maxSize;\n        this.config.rotate = this.initialConfig.rotate;\n        this.config.size = this.initialConfig.size;\n    }\n}\n";
const paginationSizeHtml = "<div class=\"vstack gap-4\">\n    <div>\n        <p class=\"small text-body-secondary mb-2\">Small</p>\n        <ngb-pagination collection-size=\"50\" page=\"example.smallPage\" page-change=\"example.selectSmallPage($event)\" size=\"'sm'\"></ngb-pagination>\n    </div>\n    <div>\n        <p class=\"small text-body-secondary mb-2\">Default</p>\n        <ngb-pagination collection-size=\"50\" page=\"example.defaultPage\" page-change=\"example.selectDefaultPage($event)\"></ngb-pagination>\n    </div>\n    <div>\n        <p class=\"small text-body-secondary mb-2\">Large</p>\n        <ngb-pagination collection-size=\"50\" page=\"example.largePage\" page-change=\"example.selectLargePage($event)\" size=\"'lg'\"></ngb-pagination>\n    </div>\n</div>\n";
const paginationSizeTs = "import { Component } from \"ngjs-core\";\n\n@Component({\n    selector: \"docs-pagination-size\",\n    controllerAs: \"example\",\n    templateUrl: \"./pagination-size.component.html\",\n    styleUrl: \"./pagination-size.component.css\",\n})\nexport class PaginationSizeComponent {\n    public smallPage = 2;\n    public defaultPage = 2;\n    public largePage = 2;\n\n    public selectSmallPage(page: number) { this.smallPage = page; }\n    public selectDefaultPage(page: number) { this.defaultPage = page; }\n    public selectLargePage(page: number) { this.largePage = page; }\n}\n";

@Component({
    selector: "docs-pagination-examples-page",
    controllerAs: "$",
    templateUrl: "./pagination-examples-page.component.html",
    styleUrl: "./pagination-examples-page.component.css",
})
export class PaginationExamplesPageComponent {
    public readonly examples = {
        basic: { html: basicPaginationHtml, typescript: basicPaginationTs },
        advanced: { html: advancedPaginationHtml, typescript: advancedPaginationTs },
        custom: { html: customPaginationHtml, typescript: customPaginationTs },
        size: { html: paginationSizeHtml, typescript: paginationSizeTs },
        alignment: { html: paginationAlignmentHtml, typescript: paginationAlignmentTs },
        disabled: { html: disabledPaginationHtml, typescript: disabledPaginationTs },
        global: { html: paginationGlobalHtml, typescript: paginationGlobalTs },
    }
}
